thebiggive/donate-frontend

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.spec.ts, src/app/app.module.ts, src/app/campaign-search-form/campaign-search-form.component.html, src/app/campaign-search-form/campaign-search-form.component.spec.ts, src/app/campaign-search-form/campaign-search-form.component.ts, src/app/campaign-summary.model.ts, src/app/campaign.service.spec.ts, src/app/campaign.service.ts, src/app/search-results/search-results.component.html, src/app/search-results/search-results.component.spec.ts, src/app/search-results/search-results.component.ts
Add initial support for a simple term search without parent / meta-campaign restrictions.
Includes:
* service to use the new search API endpoint, and summary model to capture its return format
* form at top/header of the app with validation to ensure searches happen only with 2+ letters entered
* minimal results page which just shows campaign titles for now - cards with more detail to be added next
=> DON-22 - add global campaign search

src/app/campaign-details/campaign-details.component.html, src/app/campaign-details/campaign-details.component.spec.ts, src/app/campaign-details/campaign-details.component.ts, src/app/campaign.model.ts, src/app/campaign.service.spec.ts, src/app/campaign.service.ts
@tbg-jasonfung I missed some of the type issues in review, sorry. Please keep an eye out for what should and should be an array (multiple) type.
You can also see on the CLI server if there are runtime type errors like the ones that blocked the previous S3 demo build from transpiling. I don't think these will be very common but if this happens again we can look into how we can have these caught during the CI `build` job too so this type of error doesn't get into `master`.
* Fix several places incorrectly looking for an _array of_ charities or an _array of_ campaigns when retrieving a single campaign or linked charity from a campaign (many-to-one relation)
* Update `CampaignService` spec's dummy data so it passes now that types are correct
* Add some actual test data and some more …
=> DON-15 - fix type errors blocking demo build + improve tests

package-lock.json, package.json, src/app/app.module.ts, src/app/donation-start/donation-start-offer-reuse-dialog.component.ts, src/app/donation-start/donation-start-offer-reuse-dialog.html, src/app/donation-start/donation-start.component.ts, src/app/donation-status.type.ts, src/app/donation.service.ts
* DON-10 - persist information about started donations, using local storage to persist information across app loads
* Complete JWT handling, to support getting up to date information about donations and cancelling them (both requiring authentication with the API)
* Implement `get()` and `cancel()` methods on `DonationService`
* DON-11 - warn if any found which are recent, still incomplete (after a GET check with the API) and match the project you're about to start a new donation to. Offer to resume the previous donation or cancel any reservation and start a new one
* DON-12 - process cancellations in Salesforce directly in the DON-11 case
* DON-14 - also cancel donations & reservations straight away when the incomplete matching warning has been shown and the donor chose to cancel without …
=> DON-9, DON-14 - existing donation handling & cancellations

src/app/donation-complete/donation-complete.component.spec.ts, src/app/donation-complete/donation-complete.component.ts, src/app/donation.service.ts
* Use localStorage + stabilise component bootstrapping
* Fix unstable test: By mocking the AnalyticsService properly, the new thank you page's tests passing no longer relies on luck. This should fix the test race condition properly and also lets us actually verify that the right Analytics method is called.
=> DON-72 - fix tab-dependent thank you page; fix unstable unit test

src/app/donation-start/donation-start.component.ts
Log to GA without crashing if the response is missing its `error` key. This could happen with *unhandled* Apex exceptions or gateway/connectivity issues (502s, 504s, ...)
=> DON-79 - more resilient error response handling

src/app/app.component.html, src/app/app.component.scss, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/campaign-search-form/campaign-search-form.component.html, src/app/campaign-search-form/campaign-search-form.component.spec.ts, src/app/campaign-search-form/campaign-search-form.component.ts, src/app/meta-campaign/meta-campaign.component.html, src/app/meta-campaign/meta-campaign.component.spec.ts, src/app/meta-campaign/meta-campaign.component.ts, src/main.ts
* Add general purpose in-metacampaign search
* Remove SG19-specific search demo toggle
For now, this keeps global search logic using linkable URIs but
keeps search within a meta-campaign stateful. This will mean
anybody copy/pasting from meta-campaign page would share the
base (e.g.) CC19 URI rather than a filtered view
=> More realistic meta-campaign search

src/app/app-routing.module.ts, src/app/fund.model.ts, src/app/fund.service.spec.ts, src/app/fund.service.ts, src/app/meta-campaign/meta-campaign.component.html, src/app/meta-campaign/meta-campaign.component.ts
* DON-74 - look up Fund details by their slugs
* DON-75 - add the champion Account's logo where set
* DON-76 - show the fund's contributed running total (when set in SF)
* DON-77 - show funds' title & description
=> DON-73 - use Funds API on metacampaign page

src/app/campaign.service.ts, src/app/meta-campaign/meta-campaign.component.html, src/app/meta-campaign/meta-campaign.component.ts
Rudimentary button for now that just loads a new, larger chunk of child results each time it's clicked. Hack to support the new layout and allow pseudo-paging as quickly as possible pre-CC19.
This is certainly not the way we should load extra results eventually, but I'm suggesting it as a baseline so we can continue with the design work unblocked and have a passable paging solution for CC19 if we don't get time to do more on this.
=> DON-85 - give meta-campaigns a basic 'More' button

src/app/campaign.service.ts, src/app/meta-campaign/meta-campaign.component.html, src/app/meta-campaign/meta-campaign.component.ts
* Add an _Is Doubling_ filter
* Simplify sort logic and remove pointless options
* Update labels to be more intuitive
The actual behaviour of sorting by _amount raised_ seems broken right now but I think this is the server, not the client call. Will look into that next.
=> DON-49 - improve filters + simplify sorting

src/app/campaign-details-card/campaign-details-card.component.html, src/app/campaign-details/campaign-details.component.html, src/app/campaign-details/campaign-details.component.ts, src/app/campaign.model.ts, src/app/campaign.service.ts, src/app/donation-start/donation-start.component.html, src/app/meta-campaign/meta-campaign.component.html
* Opening donations: fix date override allowing donations to campaigns with a non-Active status, when they should have opened
* Campaign detail page: fix loading and sharing metadata when there's no `summary`
* Campaign detail card: hide all target elements when there isn't one
* Campaign detail page: tidy donations closed copy & don't show empty website links
* Donate start page: tweak copy intro'ing campaign title
=> Campaign & donate page tidying & historic campaign loading fix

angular.json, src/app/hero/hero.component.scss, src/app/hero/hero.component.ts
This should fix this page usually crashing until the client takes over, which resulted from the browser-targeting webp detection in `HeroComponent` trying to run on the server too.
On browsers that do support webp, the path update should also make the background load faster. Those which don't should switch to the PNG immediately after the main page load.
=> DON-95 - fix meta-campaign (e.g. CC19 landing) server rendering

package-lock.json, package.json, src/app/donation-start/donation-start.component.html, src/polyfills.ts
The basics worked with fewer Material components in play, so hopefully the animation polyfill will get it back to being usable
=> DON-142 - add polyfills in hopes of fixing IE11

src/app/campaign-card/campaign-card.component.html, src/app/campaign-card/campaign-card.component.ts, src/app/campaign-details-card/campaign-details-card.component.html, src/app/campaign-details-card/campaign-details-card.component.scss, src/app/campaign-details/campaign-details.component.html, src/app/campaign-details/campaign-details.component.scss, src/app/campaign-details/campaign-details.component.ts, src/app/meta-campaign/meta-campaign.component.html, src/app/meta-campaign/meta-campaign.component.ts
* DON-139 - link _Championed By..._ copy through to the champion fund-specific landing page
* DON-120 - add an extra link back to the champion fund-specific landing page when a donor clicked a card from that page
* Fix a state management bug when toggling between the fund-specific and general landing pages
=> DON-120, DON-139 - back to fund-specific metacampaign links

src/app/navigation/navigation.component.html, src/app/navigation/navigation.component.scss
* Stop scrolling past menu content, in all browsers
* Fix position glitch on open in Safari
Applied the equivalent of the [suggestions here](https://stackoverflow.com/a/52704311/2803757) and it seems to have resolved both issues. Tested mobile Safari in the Simulator (iPhone 11 Pro).
=> DON-113 - fix mobile menu layout + Safari jump

README.md, package-lock.json, package.json, src/app/campaign-card/campaign-card.component.html, src/app/donation-start/donation-start.component.html, src/app/donation-start/donation-start.component.scss, src/app/meta-campaign/meta-campaign.component.scss, src/app/ticker/ticker.component.html, src/app/ticker/ticker.component.scss, src/polyfills.ts
* lay out suggested amounts in an IE11-safe way (fix donate page crash)
* remove flex column within cards
* metacampaign: have IE11 show 1 usable column instead of a completely broken layout
* make ticker IE11-friendly, hiding the animated part there with a vendor hack
* drop extra polyfills which no longer appear necessary for IE11
* document local IE debugging
=> DON-142 - IE11 fixes + bug mitigations

src/app/campaign-details/campaign-details.component.ts, src/app/donation-start/donation-start.component.ts
When donations aren't open yet but will open within 24 hours, this sets a timer for the campaign detail page to automatically switch from the dates text to the Donate button when donations open.
=> DON-132 - make campaign detail pages auto-activate

src/app/donation-start/donation-start.component.ts
This maintains the expected back button / browser history behaviour when a donor is redirect to the campaign page because the campaign's not yet opened.
=> DON-159 - replace URL state on 'not open' redirect

src/app/donation.service.ts
With the previous bogus `splice(...)` call, anything leading to a removal - including the state update on the thank you page which removes and re-adds your copy of the complete donation - could lead to other donation tokens being removed from state
=> DON-104 - fix donation state updates trashing other tokens

src/app/time-left.pipe.spec.ts, src/app/time-left.pipe.ts
This should work as intended before on the client side, while generating a single value during server rendering and having the SSR Observable resolved immediately.
=> DON-155 - SSR-safe async timeLeft pipe

src/app/app.component.spec.ts, src/app/app.module.ts, src/app/campaign-card/campaign-card.component.scss, src/app/campaign-card/campaign-card.component.spec.ts, src/app/campaign-details-card/campaign-details-card.component.spec.ts, src/app/hero/hero.component.spec.ts, src/app/meta-campaign/meta-campaign.component.spec.ts, src/app/search-results/search-results.component.html, src/app/search-results/search-results.component.scss, src/app/search-results/search-results.component.spec.ts, src/assets/scss/_mat-theme.scss, src/assets/scss/_overwrite-mat.scss, src/index.html, src/index.production.html, src/index.staging.html
This is one of a _lot_ of things I've tried tonight to get the bundled page weight down, especially for the initial CC19 landing page, which bots are refusing to parse because of the size.
I don't think it's by any means going to get rid of a majority of the page weight, but it does take out some styles that shouldn't be there (there is a warning in a guide I read specifically about not having the `mat-core` mixin included more than once) so should at least help a bit, and I think it's reasonably low risk.
=> DON-170 - remove extra modules; fix superfluous @imports; theme only the components we use

src/app/donation-start/donation-start.component.html
We want to reduce confusion from unexpectedly long delays in the campaign object view of the `matchFundsRemaining`.
We'll reinstate this when we're pulling campaign data close-to-live as planned.
=> DON-171 - temporarily hide "Match funds are currently available!" banner

src/app/campaign-search-form/campaign-search-form.component.html, src/app/campaign-search-form/campaign-search-form.component.spec.ts, src/app/campaign-search-form/campaign-search-form.component.ts
* Never disable the Search button - just make it focus the term field when the situation suggests the user hasn't finished populating it
* Treat an empty term as valid, and treat it as a clearing of the term if the box has been focused on this app load
=> DON-157, DON-173 -  improve empty search term UX

src/app/donation-start/donation-start.component.html
This should only be seen if a campaign's status and dates do not agree, as we redirect Donate to the Campaign page when it's expected to be closed based on the status
=> Add a line to indicate what's going on outside campaign dates

src/app/navigation/navigation.component.html, src/app/navigation/navigation.component.ts
From an initial local check in Chrome, removing these event
hooks doesn't seem to impact on the navigation or the icon
swap behaviour at mobile sizes, and fixes the build.
=> DON-185 - fix redundant and type-breaking nav `events` use

angular.json, package.json
This means that when CircleCI `npm run ci`s on a branch as part of
PR checks, it will also require that the static part of a staging build
completes successfully, *before* we code review changes and try
to roll them out to staging.
=> Include a static staging build in `ci` task

src/app/filters/filters.component.scss, src/app/hero/hero.component.html, src/app/meta-campaign/meta-campaign.component.html, src/app/meta-campaign/meta-campaign.component.scss, src/app/ticker/ticker.component.html
* hide scoped search & filter bars when there's 1 participating campaign
* tweak layout so this looks OK in both cases
* don't show a 0 or 1 campaign count in the ticker
=> DON-198 - improve meta-campaign page for shared campaign emergency appeals

src/app/navigation/navigation.component.html, src/app/navigation/navigation.component.ts
Use an actual navigation event, consistently, to control
menu open + close events that are navigation-linked,
removing all `(click)` events from the NavigationComponent
template except the actual state toggle button.
=> DON-202 - manage Navigation state properly

src/app/meta-campaign/meta-campaign.component.ts
This should fix the case where navigating between
two meta-campaign pages, both of which have URL slugs
set, in the same session, causes the main campaign
data to be shown from the wrong one.
=> DON-199 - fix meta-campaign state when using slugs

src/app/campaign-card/campaign-card.component.html, src/app/campaign-card/campaign-card.component.ts
This should apply in MetaCampaign and Explore page contexts
=> DON-211 - hide match funds remaining for finished campaigns' cards

src/app/donation-start/donation-start.component.html
Only show warning if No selected, so we don't make the form more verbose unnecessarily
=> DON-126 - rationalise no comms copy

src/app/campaign.service.spec.ts, src/app/campaign.service.ts, src/app/ticker/ticker.component.html, src/app/ticker/ticker.component.ts
This should now happen even when a master campaign has donations before its stated start time
=> DON-214 - have ticker count down until formal start time

src/environments/environment.production.ts, src/environments/environment.staging.ts
Just one suggestion set, which seemed to 'probably' perform
better before, shown to a higher % of donors
=> DON-220 - update suggested donation amounts

src/app/hero/hero.component.scss
The previous rule was impacting e.g. the 'find a campaign' box's
copy too.
=> Apply text shadow only where needed to improve contrast

src/app/campaign-details-card/campaign-details-card.component.scss, src/assets/scss/_mixins.scss
Align match badge on detail page same as in campaign grids,
just overlapping with the bottom of the feature image
=> DON-285 - match badge positioning

src/app/meta-campaign/meta-campaign.component.ts
When campaign desc is not set in SF
=> Fix 'null' metacampaign meta description

src/app/app.component.ts, src/app/explore/explore.component.html, src/app/explore/explore.component.ts, src/app/filters/filters.component.ts, src/app/home/home.component.html, src/app/home/home.component.ts, src/app/meta-campaign/meta-campaign.component.html, src/app/meta-campaign/meta-campaign.component.ts
- Remove unused number of cards applied event emitter
- DON-303 mimic meta-campaign query params approach on explore component + conditionally show clear filters button
- Conditionally show clear filters button on meta campaign component
- DON-303 reinstate search component on home page which now navigates to /explore page + remove globalSearch method
=> DON-303 explore search query params

src/app/donation-start/donation-start.component.scss, src/assets/scss/_overwrite-mat.scss
Make mat form field inputs more prominent + add override border and lose underline when not focused
=> DON-307 donation input field prominence

src/app/explore/explore.component.ts, src/app/meta-campaign/meta-campaign.component.ts
DON-354 relax flag which stopped route updates from re-querying old search results
I think this flag was part of this [379](https://github.com/thebiggive/donate-frontend/pull/379/files) which addressed [DON-348](https://thebiggive.atlassian.net/browse/DON-348) - this flag shouldn't affect the the unexpected filter logic behaviour and I can't seem to replicate that location filter issue locally whilst the flag was removed.
=> DON-354 relax flag which stopped route updates from re-querying old search results

src/app/donation-complete/donation-complete.component.html, src/app/donation-complete/donation-complete.component.ts, src/app/donation.service.ts
* make Donation service `removeOldLocalDonations()` public
* use it on thanks page prior to trying to load donation data from the API
* account for this case in no access error message copy
=> DON-356 - fix crash when old donation thanks page viewed

src/app/meta-campaign/meta-campaign.component.html
I saw this early in CC20 when loading more campaigns by scrolling on an unstable connection
Not urgent
=> More helpful not loaded message

src/app/navigation/navigation.component.scss
Protect other browsers from weird behaviour as a result of this new rule
=> REG-9 - limit IE11 fixed position rule with a selector hack

src/app/donation-complete/donation-complete.component.html
Minor fix to sort out the non-metacampaign-context "Explore other campaigns" link. Previously this went back out to (always Production) SF Communities, which then redirects back to the Donate app's home (not explore) page.
=> Fix donation complete Explore link

src/app/donation-start/donation-start.component.ts
Resolve donation local state being replace erroneously with
a new and incomplete copy, for certain permutations of going
forward and back in the stepper
=> DON-368 - fix tip changes

package-lock.json, package.json, src/app/donation-start/donation-start.component.html, src/app/donation-start/donation-start.component.spec.ts, src/app/donation-start/donation-start.component.ts, src/app/stripe.service.ts
* expose a required billing country field, defaulting to GB, for Stripe
* use this in place of fixed 'GB' for data passed to Donate API & Stripe
* use a simplified, looser pattern requirement for billing postcode
=> DON-388 - support any donor country

server.ts, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/country-code.token.ts, src/app/donation-complete/donation-complete.component.spec.ts, src/app/donation-start/donation-start.component.ts, src/app/donation.service.spec.ts, src/app/donation.service.ts, src/app/stripe.service.spec.ts
After many experiments and re-builds of the Docker-ised version of the app, I _think_ this should now successfully get the default country passed through at runtime to components that inject `DonationService`.
I mostly tested by temporarily replacing the fallback used in place of `req.header('CloudFront-Viewer-Country')` with a test alternative string.
Once it passes code review, I think the next step to get a good sense of whether this works in practice is to get it and the corresponding infra changes through to Staging, and the test using proxies or other ways to generated test traffic from different countries.
=> DON-387 - detect country & set it as default

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.ts, src/app/campaign-details/campaign-details.component.html, src/app/campaign-details/campaign-details.component.ts, src/app/campaign-list.resolver.ts, src/app/campaign.resolver.ts, src/app/charity-campaigns.resolver.ts, src/app/donation-start/donation-start.component.html, src/app/donation-start/donation-start.component.spec.ts, src/app/donation-start/donation-start.component.ts, src/app/home/home.component.html, src/app/home/home.component.spec.ts, src/app/home/home.component.ts, src/app/meta-campaign/meta-campaign.component.html, src/app/meta-campaign/meta-campaign.component.spec.ts, src/app/meta-campaign/meta-campaign.component.ts
Also simplify some stuff by not needing to check for `campaign[s]` presence so much, and having a general route changed spinner instead of route data specific ones.
=> DON-223 - add route resolvers; improve Donation Start tests

package-lock.json, package.json
From https://github.com/puppeteer/puppeteer/releases/tag/v10.0.0 it looks like the tag I've used may bring Chromium up to 92, but divergence this way around seems to be OK – and this should presumably give us an additional ~6 weeks before the following Chrome version goes stable and builds start downloading an incompatible ChromeDriver.
=> Update Puppeteer for Chromedriver 91

src/app/campaign.resolver.ts, src/app/charity-campaigns.resolver.ts
Also try to avoid sending some invalid format slugs as requests to SF at all.
=> DON-412 – handle resolver errors (e.g. missing slugs) without a server crash

src/app/donation-start/donation-start.component.ts
Provide more helpful feedback for donors and TBG support
to identify what has gone wrong in the different Stripe
failure modes.
=> Add Stripe error message prefixes

src/app/stripe.service.ts
Note that the remaining `await loadStripe(...)` is designed to do the library load that the head tag was doing. When I removed the fixed Stripe load from the `index.html`s it looks like it could/should actually have been a clean removal because of this, and there was no need to do DIY script tag loading in the TS like we do for Analytics and Get Site Control.
=> DON-417 - fix `init()` loading Stripe 2 different ways

src/app/multicurrency-landing/multicurrency-landing.component.html, src/app/multicurrency-landing/multicurrency-landing.component.scss
@alihejazi I noticed Staging GG1 glitching on server load (big blank space) and looked at the server logs. This PR updates the asset paths refs to use the same approach as the rest of the app, which should make asset path refs work in both the Express server / dynamic ECS version of the app, and the client-side bundle.
=> Fix GG1 asset paths breaking SSR loads

src/app/meta-campaign/meta-campaign.component.ts
* introduce a 10 minute cutoff to avoid reinstating old child campaign data
* hopefully make handover to saved campaigns slightly smoother / show loading spinner earlier
=> DON-457 – fix saved child campaigns

src/app/donation-start/donation-start.component.ts
Shaky new logic is possibly implicated in an uptick today
in live edge case blips from API calls getting through in unexpected
orders.
=> DON-467 - avoid donation re-create blips

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/campaign-promo-card/campaign-promo-card.component.html, src/app/campaign-promo-card/campaign-promo-card.component.scss, src/app/campaign-promo-card/campaign-promo-card.component.spec.ts, src/app/campaign-promo-card/campaign-promo-card.component.ts, src/app/campaign-promoted-1.resolver.ts, src/app/campaign-promoted-2.resolver.ts, src/app/explore/explore.component.html, src/app/explore/explore.component.spec.ts, src/app/explore/explore.component.ts, src/app/home/home.component.html, src/app/home/home.component.scss, src/app/home/home.component.spec.ts, src/app/home/home.component.ts, src/app/promoted-campaigns/promoted-campaigns.component.html, src/app/promoted-campaigns/promoted-campaigns.component.scss, src/app/promoted-campaigns/promoted-campaigns.component.spec.ts, src/app/promoted-campaigns/promoted-campaigns.component.ts, src/environments/environment.production.ts, src/environments/environment.regression.ts, src/environments/environment.staging.ts, src/environments/environment.ts
@alihejazi this is ready for an initial code review and I suggest we do that now. It should however remain in draft for right now as we're blocked on two points before it can be considered for live release:
1. Asset sizes should be consistent with past metacampaigns – this is why the CC21 banner doesn't quite align currently
2. The hard-coded slugs need to be changed from CC21's to the Ukraine one, but only once that campaign exists in Production and Full – until then the resolver will fail and block loading the Home and Explore pages
=> DON-487 - add promoted metacampaigns banner

src/app/donation-start/donation-start.component.ts
* reset state more thoroughly when donations are cancelled
* also clear Stripe.js element data for now, to reduce the chance
of incorrect Payment Method reuse in error edge cases
* listen for card changes in the latest documented way
* use Stripe.js types better
=> DON-496 – more robust donation resets and Stripe event listeners

.circleci/config.yml
Trying a major version we use elsewhere, that should be new
enough not to break with old base image removals, and not so
new as to not be working as documented!
=> DON-506 – "downgrade" ECR orb to v7.x

src/app/donation-start/donation-start.component.html, src/app/donation-start/donation-start.component.ts
* [DON-270 – more stable Stripe.js card input renders](https://github.com/thebiggive/donate-frontend/commit/25103939bbebe808e683fa8c468c8059bbad58f7)
1. Always have an `ElementRef` but hide the el when needed
2. Show it on any non-`true` value for `useSavedCard` instead of only strictly `false`
* [DON-270 – ask Stripe.js to set up the card input more proactively](https://github.com/thebiggive/donate-frontend/commit/d3d7843bda63adfe5dad33b60daf74a9704ac6ec)
* [DON-270 – set stripePaymentMethodReady reliably when defaulting a saved card to on](https://github.com/thebiggive/donate-frontend/commit/7cb4f7afc9c4d20e17d3ae7466c218d451df8461)
* [DON-270 – set useSavedCard to false (not null) when doing a full form reset](https://github.com/thebiggive/donate-frontend/commit/f91c26d4f5a9ab9dbd709d2b …
=> DON-270 – card input + validation edge case fixes

src/app/app.component.ts, src/main.ts
Locally I added console logging to this and did the SSR Docker builds described in the readme. It seemed that the browser was able to respond to loading events appropriately while the server no longer logs errors.
=> DON-536 – fix `document` global server bailouts

.circleci/Dockerfile
Latest `lts` tag as of this week (presumably newer) fails to run `apt-get` updates with lock file permission errors, which we don't have time to dig into right now.
=> Pin container build to Node 16.18

src/app/donation-start/donation-start.component.html, src/app/donation-start/donation-start.component.ts
* Resolve JS crash from missing Payment Request Button element under some conditions
* Ensure amount is always loaded as an int, so that `===` checks work as intended
* Don't require billing address or country when using credit as no new
=> DON-533 – credit use QA fixes

src/app/stripe.service.ts
We have to do a slightly weird type dance because TS needs its `parseInt()` inputs to be strings.
This should stop Stripe PRB logic crashing because it's given 8099.9999999 pence or similar.
=> DON-690 – fix float value errors in some PRB cases

src/app/donation-start/donation-start.component.ts
I'm not really clear why it passes the majority of the time/ not all the time, but I'm hoping this will fix the remaining regression tests still getting _"Missing data from previous step – please refresh and try again"_ when pressing the final Donate button as a donor with a saved card.
In theory `this.card` should be set up for every Stripe donate page, but it seems like perhaps there's an intermittent timing issue or something when the element is not actually made visible?
=> Ensure a saved card is always a sufficient ready-to-Donate criterion

src/app/donation-start/donation-start.component.ts
Notably, permit subdomains. Also allows a couple of known odd things like "." straight after "@" in the interest of speed + simplicity.
=> DON-698 – simplify and loosen validation of email addresses' domain part

src/app/campaign-details/campaign-details.component.ts, src/app/explore/explore.component.ts, src/app/meta-campaign/meta-campaign.component.ts
As discussed, I think shortly after CC22 we should refactor this so we don't have so much extra logic in `<biggive-button/>`. But for now, we should sort out the existing prop approach so that close times are factually correct.
=> Fix the hour in various `getRelevantDateAsStr()`s

src/app/identity.service.ts, src/app/reset-password/reset-password.component.html, src/app/reset-password/reset-password.component.ts
This PR relies on https://github.com/thebiggive/identity/pull/44 so that should be merged first.
We show the error below instead of the new password form if someone clicks a password reset link that has expired or doesn't exist.
Ideally like to make it an actual 404 error page, but I'm not sure how to persuade react router to do that, and this way may be fine, especially since we don't seem to serve a 404 page anywhere at the moment.
=> DON-273: Show error instead of password reset form if token invalid

src/app/charity/charity.component.ts
This page was added largely to give search engines a meaningful "charity index" as we moved from legacy – but it has no title! Quick short-term fix for that here, ahead of us spending a bit more time making the page more useful for humans.
=> Fix page metadata for charity landing page

package-lock.json, package.json
I ran `FONTAWESOME_NPM_AUTH_TOKEN=***** npm update` to make this change.
This brings in recent menu changes from [COM](https://github.com/thebiggive/components/)
=> Update components to version 1.0.181

src/app/app.component.scss, src/app/app.component.ts
Global styles are already loaded in `angular.json` so they seem to have been extraneous here. Removing this decreases the `main` bundle's uncompressed size quite a bit.
=> Stop loading global styles both globally and on `AppComponent`

.circleci/config.yml
We may want to restore this in future, but removing for now as it has been failing for several days
=> Remove failing Jira notification step.

src/app/donation-complete/donation-complete-set-password-dialog.html
I think we probably don't need it, and we don't have a way to make sure this is up to date with any backend changes that set the duration. I noticed this by chance.
=> ID-35: Don't specify login duration on login

src/app/app.component.ts
The redirect from new domain back to old domain was losing the secret token as that was in a query parameter and not part of the pathname
I've tested out assigning window.location.host in the browser console instead and that works.
=> Fix BG2-2285: Donor password reset link not working

src/app/my-account/my-account.component.html, src/app/my-account/my-account.component.scss, src/app/my-account/my-account.component.spec.ts, src/app/my-account/my-account.component.ts
I think this might be all we need for display of payment methods. There is more information that we have, and that the API is sending to the browser so people can see if they no how, but I think things like the billing address attached to each payment method and what country it's in would just clutter the page if we showed them here.
This is how the page looks if you have several cards saved:
I'm pretty sure we don't allow any payment methods other than cards, but if someone does have a different method stored (e.g. [Cleaplay](https://www.clearpay.co.uk/en-GB) then it would be displayed like this:
If people agree that this is enough for the display I'll move on to implementing deletion.
=> DON-727: Improve payment method layout

src/app/app.component.html
This matches what we have on wordpress site, as well as casing of other menu items
=> Fix title case in menu

.circleci/config.yml
See https://github.com/CircleCI-Public/aws-ecr-orb/releases/tag/v8.0.0
Build failed at https://app.circleci.com/pipelines/github/thebiggive/donate-frontend/3207/workflows/5e1edb79-9b2a-44a8-99c4-0e8f2e266e8e because the orb now wants the regions as a string, not an env variable.
=> DON-741: Update Circle config to work with aws-ecr-orb 8

.circleci/config.yml
We're getting an error code 60 (CURLE_PEER_FAILED_VERIFICATION). Don't know why, but updating the orb seems like a good start to fixing it.
=> Update slack notification orb

src/app/donation-complete/donation-complete.component.scss
Updated screenshot (as will be shown when this PR and https://github.com/thebiggive/identity/pull/70 are merged):
=> ID-36: Make registration error warning triangle more prominent

src/app/donation-complete/donation-complete-set-password-dialog.component.ts, src/app/donation-complete/donation-complete-set-password-dialog.html
It looks like the "Log me in" function within the donation complete page has not been working since January. IMHO whenever something is not working at all we should immediately fix or remove it. I don't have a fix ready to apply so this removes it instead.
Before:
After:
=> Remove login after donate

.circleci/config.yml
Hold step was only introduced because I was nervous about issue DON-741, I don't think its needed now.
=> Remove hold step in production deploy

src/app/donation-start/donation-start.component.html
Previous button was not visible as a button in the non-hover state, and the text was not readable in the hover state
=> DON-717: Set colour of Donate button

src/app/donation-start/donation-start.component.ts
Repeats code as written yesterday, then just adds a check to make sure we don't unnecessarily prompt for the captcha when the donation object is already created.
=> Don 759 take ii

src/app/home/cardsForMetaCampaigns.spec.ts, src/app/home/cardsForMetaCampaigns.ts, src/app/home/home.component.ts
Reverts thebiggive/donate-frontend#1055
Seems like this is already showing on production. I don't understand why or how:
=> Revert "Don 761 gmf card update"

server.ts
Allow our Matomo host for `connect` and `img` sources too, based on observed CSP errors and
https://matomo.org/faq/general/faq_20904/
=> DON-758 – Matomo CSP additions

src/app/update-card-modal/update-card-modal.component.scss, src/app/update-card-modal/update-card-modal.component.ts
Given we have intermittent CI build issues for the “real” app currently, and the other highly rated answer on https://stackoverflow.com/questions/65537399/angular-11-stuck-on-generating-browser-application-bundles-phase-building/68163709#68163709 mentions empty CSS files, it seems worth a go to also retire the 1 we added recently.
c.f. https://github.com/thebiggive/donate-frontend/pull/1066
=> Remove empty style file, unused imports

src/app/donation-start/donation-start.component.html
Now the first next button on the donation start form is greyed out unless and until a donation amount between £1 and £25,000 is entered. Looks like this just needed a one line change.
=> DON-766: Prevent attempts to create invalid donation

src/app/donation-start/donation-start-form/donation-start-form-new.component.scss
Steps towards new stepper design:
- White background for headers
- Green triangle icons
- No vertical line through stepper
=> DON-610: New donation stepper: white headers, green icons, no line

src/app/conversionTracking.service.ts
Despite the library docs, currently an undefined category makes it skip setting the value of a line item
=> DON-782 – Matomo: fix line item ecommerce amounts not set

src/app/reset-password/reset-password.component.html, src/app/reset-password/reset-password.component.ts, src/app/reset-password/reset-password.module.ts
* Define modules consistently in one place
* Do routing the same as other pages
* Remove redundant `MatDialog` container stuff
=> Fix "finish password reset" page being sort-of-standalone

src/app/donation-start/donation-start-form/donation-start-form-new.component.html, src/app/donation-start/donation-start-form/donation-start-form-new.component.ts, src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts, src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.ts
If a custom tip outside of the min / max suggested percentage is selected, then we don't allow people to go back to the slider
=> DON-791: Update tip slider with value set in custom tip field

src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.ts
Writing the margin as a percentage means it doesn't matter if this code runs before we know the width of the container
It now looks like this on page load:
The appearance after an amount has been input as on staging:
=> DON-794: Load slider with handle in correct position

src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts
May be worth doing a bit more work to consolidate all the writes to DonationStartFormParentComponent.stripePaymentMethodReady
We might be able to put
`this.stripePaymentMethodReady = !!this.selectedSavedMethod || this.stripeManualCardInputValid || this.creditPenceToUse > 0;` into a function and call that whenver those other things change - as longs we make sure they are all updated as required first. Or we could call it directly from template but that might be bad for performance
=> Fix DON-817: Can't donate using donation credits account

src/app/donation-start/donation-start-form/donation-start-form-new.component.html, src/app/donation-start/donation-start-form/donation-start-form-new.component.scss
All the next buttons and the confirm button are styled the same
=> DON-809: Make next button styling consistent on all steps of new stepper

src/app/donation-start/donation-start-form/donation-start-form-new.component.html, src/app/donation-start/donation-start-form/donation-start-form-new.component.scss, src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts
As clearing the custom tip input would remove the ability to go back to the slider if we kept hte existing behaviour that the slider is only available when the custome input is within the 1%-30% range, I changed the logic to make make the link to return to the slider always available, and when the user goes to the slider we adjust their tip to be the closet to what they have selected that lies within that 1-30 range.
=> Don 815 no default custom tip

src/environments/environment.production.ts
Switch the Matomo "website" to which we track at exactly the start of 30 June (BST)
=> DON-825 – timed Matomo site swap

src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.ts
Currently the label has a bit of a weird retrograde movement on the right hand side. This should keep it always moving in the same direction as the slider handle.
=> DON-814: Adjust position of tip slider label near right hand edge

src/app/donation-start/donation-start-form/donation-start-form-new.component.html, src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts
To test this add `?tipControl=dropdown` on to the address bar when looking at the new stepper - this will replace the slider control with a drop down control. We still need to work out how to run an a/b test of the two, but probably worth getting the implementation with the dropdown selected this way QA'd first.
The edges of the input are a bit finicitky and can disappear depending on zoom in Firefox - but I think that's a generall issue with all these dropdowns, not specific to tipping.
Screenshots as on Jira:
=> DON-788: Allow switching between tip slider and drop-down

src/app/donation-start/donation-start-form/donation-start-form-new.component.html
As discussed this text unecassarily repeats the conent of the slider tooltip. Also removed a 50px margin that we don't need.
Before:
After:
Drop down version is largely unchanged:
=> New stepper: Remove £x.xx donation to support Big Give text above slider

src/app/donation-start/donation-start-container/donation-start-container.component.html
This duplicates information that we show within the new donation stepper
Before:
After:
=> Don't show donation header with new design

src/app/campaign-card/campaign-card.component.ts, src/app/campaign-info/campaign-info.component.ts, src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts, src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.ts, src/app/donation-start/donation-start-login/donation-start-login.component.ts, src/app/donation-start/donation-start-secondary/donation-start-secondary.component.ts
Taking advantage of the new feature in Angular 16 to express when an input is always set. This gets checked at compile time in all templates that use the component
See https://netbasal.com/from-good-to-great-required-inputs-in-angular-47374c8a43cf
I dif a fairly niave search for all the @Input decotators and added required - then took it away anywhere it triggered a compile error. Seems reasonable to assume that if we currently allways pass an input to a componen then it's probably required.
=> Refactor: Required-input all the things

src/app/donation-start/donation-start-form/donation-start-form-new.component.scss
See e.g. https://stackoverflow.com/a/2875030
I'm also wondering if there's a better place to put this code to mkae it not specific to the donation page.
And on the other hand whether there's a good enough reason for browsers to bring their own default styling to input fields that means we should leave it alone. But I know using css-reset files is a widespread practice. I couldn't really find any description of exactly why input elements have font family set by browsers.
=> DON-810: Inherit site font into input fields in new stepper

src/app/donation-start/donation-start-form/donation-start-form-new.component.scss, src/app/donation-start/donation-start-form/donation-start-form-new.component.ts, src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts, src/app/stripe.service.ts
Changes as discussed in last comment on Jira: https://thebiggive.atlassian.net/browse/DON-810?focusedCommentId=31188
Before:
After:
Before:
After:
Also note the font family inside the payment card input isn't as it should be above - but that seems to just be an issue with the local dev environment. It should be fine when we deploy this code to staging / prod.
Note the font size of the country drop down "United Kingdom" is still 17px rather than 18 - this will need changing in the component library. Easiest change is to just make it 18px there - that will also affect the filter drop downs in the explore page, which may be OK, or we could make it inherit a font size or allow passing one in. I guess it's not ideal that we're picking sizes looking at one page at a time rather than properly …
=> DON-810: Adjust new stepper font sizes: Header and payment card inputs

src/app/transfer-funds/transfer-funds.component.html, src/app/transfer-funds/transfer-funds.component.ts
This relies on matchbot changes at https://github.com/thebiggive/matchbot/pull/577 to be useful, but the PRs can safely be deployed in either order - matchbot will just ignore the additional fields at the moment.
There are no changes here visible to the donor, but after donating (given the matchbot changes is also present) the entry in the matchbot DB looks like this:
=> DON-706: Store donor dator on transfer funds tip

src/app/donation-start/donation-start-form/donation-start-form-new.component.scss
Remove `float: right` which makes right padding
significant, and variable across browsers. And reset `padding` to 0 to further improve consistency
across browsers.
=> DON-816 – fix odd layout on new inputs

src/app/donation-start/donation-start-container/donation-start-container.component.scss
Not sure if there's a better way based on putting the banner in a separate stacking context to the eyebrows instead of increasing Z
Before:
After:
=> DON-838: Increase match fund banner z index

src/app/donation-start/donation-start-container/donation-start-container.component.scss
Before:
After:
I would ideally like to get rid of the tiny bit of black visible on the right edge as well, but that seems fiddly and not sure how much time it's worth right now.
=> DON-838: New stepper / Reduce match funding banner to fit on mobile

src/app/donation-start/donation-start-form/donation-start-form-new.component.html
Not sure why it wasn't working here specifically, but telling the browser exactly what we want autocompleted seems to fix it. I tested with 1password on my local
=> DON-834: Fix autocmplete not working on email in new stepper

src/app/app-routing.ts
We are not quite ready to direct traffic to the new stepper, but we are ready to start testing it in production ourselves.
When this is deployed URLs such as https://donate.biggive.org/donate-new-stepper/a056900002PoxFoAAJ should work in production to show the new stepper instead of redirecting to the homepage as it does now.
=> DON-787: Enable use of new stepper for testing in production

package-lock.json, package.json, src/app/donation-complete/donation-complete.component.html, src/app/donation.service.spec.ts, src/app/donation.service.ts, src/app/identity.service.ts, src/app/meta-campaign/meta-campaign.component.ts
This means the thank you page will now only be viewable in the same tab where the donation was made, and not at all after the tab is closed. While it might be nice to have the thank you page available for longer I think this is OK and avoids storing more info in the browser than we need. Donors should be able to see all the details of their old donations in their emails.
Session storage is scoped to the browser tab and automatically expires when the tab is closed, whereas local storage never expires.
Ideally I would like something that persists for the session only (or for a short time like 1 day) but is available across all tabs. That seems more work to set up, would perhaps require using a cookie and relying on the server side db for the content instead.
=> DON-783: Save donations & campaigns in session storage not local storage, save ID & JWT in cookies

src/app/app-routing.ts, src/app/donation-start/donation-start-container/donation-start-container.component.ts
Every `donate` page now shows our new design not the old one.
The old one is available for anyone who wants to see it at /donate-old-stepper/<campaignID> but I expect we'll delete that very soon.
=> DON-787: RELEASE NEW DONATION STEPPER

.circleci/config.yml
The point release I tried before is not supported on our current resource class
=> DON-871 – don't specify remote Docker version

.circleci/config.yml
With tag matching the default from this same env that built last
=> DON-871 – try to `--cache-from` the last good ECR build

src/app/donation-complete/donation-complete.component.html
No-one's likely to care what second they made their donation, and it's one less thing to listen to for screen reader users
=> DON-870: Stop displaying seconds in reciept on thank you page

.circleci/config.yml
Try to use the ECR orb's default machine-based approach, but with ECR as the explicit layer cache source
=> DON-871 – remove remote Docker cache config

src/app/campaign-details/campaign-details.component.spec.ts, src/app/campaign.model.ts, src/app/campaign.resolver.ts, src/app/campaign.service.spec.ts, src/app/donation-start/donation-start-container/donation-start-container.component.spec.ts, src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/meta-campaign/meta-campaign.component.spec.ts
Groundwork for dropping this deprecated, redundant property from all apps.
And other minor refactoring.
=> Stop passing `donateLinkId` around

src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.ts
Going back to the first step indicates that they may be about to change the donation amount, and we have a bug that means changing the amount makes the confirm payment step at the end fail. This avoids that, at the (high but worth paying) cost of erasing what they've typed into the form. 
It's not a good solution by any means, but I've now spent a full day trying to find a better solution, and not found one. This is a lot better than nothing, and doesn't stop us looking for a better solution.
The one fix I managed to find for the original bug has the side effect of requiring the donor to type in their payment details a 3rd time (after the expected 2nd time that happens because they changed the amount). That's confusing and I think worse than the change here.
The only other option I can …
=> Don-883: Reset donation form if donor goes back to first step

src/app/donation-start/donation-start-form/donation-start-form.component.ts
This should avoid the problem we're seeing in regression tests of being prompted to continue the existing donation, which would be a bit confusing and also makes the tests fail
=> DON-882: Cancel donation before reloading stepper at first step

src/app/app.component.html, src/app/app.component.ts
If it renders on the server then the browser just has to un-render it for people who don't need it, which leads to an ugly flash of content thats pasturize before you can read it.
=> DON-783: Only render cookie consent banner on browser

src/app/donation-start/donation-start-form/donation-start-form.component.ts
We display our own terms, so these should not be necassary
=> DON-880: Don't display terms for apple pay or google pay, adjust matomo event for wallet payments

cypress.config.ts, cypress/e2e/spec.cy.ts, cypress/support/e2e.ts
Makes the frontend a little more self-contained, although we lose some incidental testing of the SF API
=> DON-614: Intercept HTTP call to SF API in cypress tests

cypress/e2e/spec.cy.ts
It seems like due to Chrome behaviour(?) Cypress "eats" the extra slash, but it could confuse devs comparing it to how the real app builds this.
=> Don't build a `//` URI where the real app doesn't

src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/donation.service.spec.ts, src/app/donation.service.ts, src/app/stripe.service.ts
And rationalise what we reset, leaving an already valid Payment Element
and its status tracking properties untouched where possible.
Plus related small tweaks & fixes.
=> DON-883 – keep Stripe.js in sync with the Donation

src/app/home/home.component.ts
As of now this keeps the homepage unchanged like so:
but by changing the date mentioned at line 63 to one in the past it appears like so:
=> DON-874: Advertise Arts For Impact from the 9th of October

src/app/donation-start/donation-start-container/donation-start-container.component.spec.ts, src/app/donation-start/donation-start-container/donation-start-container.component.ts, src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts
Use a lifecycle hook that can safely assume `@ViewChild`ren are instantiated.
=> Make resume calls on `DonationStartFormComponent` safe

src/app/app.component.html, src/app/app.component.scss
This button is visible only when it is focused - at other times it hidden off the edge of the screen.
I used the #focus-within CSS selector, which should work with all browsers except IE and Opera Mini.
=> DON-889: Add Skip to Content link

src/app/donation-complete/donation-complete.component.ts, src/app/identity.service.ts
Try up to 3 times with a fixed 2s gap. Updates should be harmless to double send and this should reduce the frequency of edge cases where Stripe is missing customer info.
=> DON-901 – retry ID service updates on failure

src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.ts
Message now pops up every time the donor tries to continue from this step without filling in their choices:
=> DON-819: Use snackbar to show errors in stepper recieve updates step

src/app/campaign-info/campaign-info.component.ts, src/app/campaign.service.spec.ts, src/app/campaign.service.ts
For shared fund child campaigns, make the progress % reflect the parent, like the related numbers next to the bar, where applicable.
=> DON-906 – fix some Campaign Info progressbars

src/app/app.component.html, src/app/app.component.scss, src/app/app.component.ts
Taking the router.url in the template constructor doesn't work, the router doesn't know what page we're on that early. We need to react to router events instead.
Also I think the push button is not quite as easy to use as a simpe a tag, so as discussed have take away the biggive-button here and put in A tag with some simple custom styling instead:
=> DON-889: Fix Skip to content link

src/app/donation-start/donation-start-form/PaymentReadinessTracker.spec.ts, src/app/donation-start/donation-start-form/PaymentReadinessTracker.ts, src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/featureFlags.ts
Instead of a greyed out continue button at the payment step, we now have an active button that triggers display of all errors in the section the donor isn't ready to continue:
The errors are shown both in a toast message to get immediate attention, and above the button to allow the donor to review them as they edit the form:
=> DON-819: Show errors blocking progress from payment step

src/app/donation-start/donation-start-form/donation-start-form.component.ts
Reverts thebiggive/donate-frontend#1344
1344 seems to make it impossible to proceed backwards and then fowards through an invalid form, which is a standard workflow we have to support.
=> Revert "DON-909: Show message for unexpected errors blocking stepper.next, in…"

src/app/app.component.html, src/app/app.component.scss, src/app/donation-start/donation-start-container/donation-start-container.component.html, src/app/donation-start/donation-start-container/donation-start-container.component.scss, src/app/donation-start/donation-start-form/donation-start-form.component.scss
It was previously being lost under the reserved funds banner on desktop, making all sub-items unreachable
=> DON-902 – fix submenu not usable

src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/donation.service.spec.ts, src/app/donation.service.ts
* [only offer reuse of donations with the active `paymentMethodType`](https://github.com/thebiggive/donate-frontend/pull/1361/commits/7a902dd55514ea292ac8c397adc12c26f19daa89)
[7a902dd](https://github.com/thebiggive/donate-frontend/pull/1361/commits/7a902dd55514ea292ac8c397adc12c26f19daa89)
* This should avoid the donate form breaking in edge cases like donors
who started one donation recently, then later topped up with new funds
* [update error copy, reflecting the remaining way we know paying with donor funds can fail](https://github.com/thebiggive/donate-frontend/pull/1361/commits/1008caa2458d688125b634596e708bc08625e8a4)
[1008caa](https://github.com/thebiggive/donate-frontend/pull/1361/commits/1008caa2458d688125b634596e708bc08625e8a4)
=> DON-820 – avoid & better report errors paying with donation funds

src/app/transfer-funds/transfer-funds.component.html, src/app/transfer-funds/transfer-funds.component.ts
* set tip numbers to 0 explicitly as an existing tip's detected
* add an extra check to prevent creating another tip if form data somehow gets out of sync
=> DON-596 - fix logic when a tip is pending

src/app/donation-start/donation-start-form/donation-start-form.component.html
Removing the empty panel doesn't change the appearance of the page.
Not sure why this panel was there, but it's empty and has no code comment to explain its purpose and is confusing when using keyboard navigation and screen reader, so removing
Adjusted confirmation text at the end of the page looks like this:
=> DON-876: Donation start page a18y improvements

src/app/donation-complete/donation-complete-set-password-dialog.html, src/app/donation-complete/donation-complete.component.html
- Stop auto-focusing on the 'cancel' button so it doesn't have to be read first
- Set entire dialog content as 'aria-live' so it is automatically read out when the dialog is opened
- Change link copy from "Learn more" to "Learn more about stripe"
=> DON-877: Save my details dialog screen reader adjustments:

src/app/meta-campaign/meta-campaign.component.ts, src/app/my-account/my-account.component.ts
Only allow setting it client-side, and clear
it when appropriate.
Also fix a typo in a similar bit of metacampaign
cleanup
=> DON-904 - tweak new My Account timeout

src/app/home/HighlightCard.ts, src/app/home/home.component.html, src/app/home/home.component.ts
To test, with a simulated current date, visit a URL such as http://localhost:4200/?simulatedDate=2023-11-28T12:00:00%2B00:00
The number at the end after `%2B` is the timezone offset from UTC - so keep it at zero if you just want to test for London in winter.
=> Don 918 update homepage

src/app/app-routing.ts, src/app/login/login.component.cy.ts, src/app/login/login.component.html, src/app/login/login.component.ts
Login page is at `/login`
Includes function to redirect the user to any other page on the site if `?r=<redirectTarget>` is added to the URL. My plan is to use a router guard to redirect attempts to access pages like `my-account` to `/login?r=my-account`
=> DON-752: Create login page

src/app/donation-start/donation-start-form/donation-start-form.component.ts
Bypass can happen by pressing escape or clicking outside a puzzle. The best way to test this is by [setting a bot-like User Agent](https://stackoverflow.com/a/50955485/2803757) or using TestingBot to get more puzzles.
Should avoid situations where the donor gets to 'Payment details' but the Stripe.js element has not been set up.
=> DON-938 – fire captcha again when we can detect that it was bypassed

src/app/donation-start/donation-start-form/donation-start-form.component.ts
Give it a more explicable donor toast & log event, now we know the remaining reason that former "code B1" can happen.
=> DON-937 – update invalid form messaging

src/app/donation-complete/donation-complete.component.ts, src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/donation.model.ts
* fix the condition for showing last-resort 'no captcha' error message in 'Payment details' step – our goal is still to make it impossible to see this through earlier step change checks & restrictions
* fix attempts to create undefined amount donations if amount field's empty
* jump back to 'Your donation' step only when we need to collect a [new] amount
* fix when we show a "toast" when dismissed captchas mean donor has got to a point
that can't work;
and jump back a step then too to avoid showing unusable fields
* invoke the captcha from the same common place in code, with the same associated
state changes, every time
* pick up on stepper header clicks more reliably
* check for `this.donor` when assessing captcha readiness, since if we have a valid
donor already we don't need to issue …
=> DON-938 – rationalise various captcha + step management

src/app/reset-password/reset-password.component.html, src/app/reset-password/reset-password.component.ts
This will be better with accompanying changes in Identity, but should be fine to deploy independantly first
Changes:
- Treat the error message from the server as HTML, so that it can include a link to our privacy policy
- Don't hide the form when the error message is displayed, so the donor can try again.
With the changes in identity, if I try to set my password to "correct horse battery staple" then I get this:
When this is deployed without the accompanying changes in identity server, it will initially look like this:
=> BG2-2526: Improve reset password error display

src/app/donation-complete/donation-complete.component.ts, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/identity.service.ts, src/app/login-modal/login-modal.component.ts, src/app/login/login.component.ts, src/app/register-modal/register-modal.component.ts
I tried to make saveJWT a private function but that led to test errors - not sure exactly what was going wrong in that commit. See https://app.circleci.com/pipelines/github/thebiggive/donate-frontend/4857/workflows/cd11916a-8540-4abd-bf3f-d47932774f73/jobs/13879
But this goes part of the way, adding the call to saveJWT inside IdentityService.login so that callers to that don't need to also call saveJWT.
=> DON-752: Refactor: try to privatise IdentityService.saveJWT

src/app/home/home.component.ts
Screenshot as it looks now (same as in prod already):
Screenshot with simulated future date of Jan 10th:
http://localhost:4200/?simulatedDate=2024-01-10
And then on Feb 1st it will show
And with a simulated date after Feb 9th it looks a bit empty but probably we'll have put something else in before that happens:
=> DON-919: Update homepage cards - 2024 application season

src/app/my-account/my-account.component.html, src/app/my-account/my-account.component.scss, src/app/my-account/my-account.component.ts
Per comments on ticket.
I don't quite like the placement of "Log out", as it doesn't vertically align with anything. I think eventually we might want to remove it from here and put it in the main menu instead, but that should probably be considered out of scope of the current ticket.
It's not shown in the screenshot above because I deleted my card from my local, but the card edit and delete buttons are changed from buttons to white underlined text links. We should check how they work with screen readers.
=> DON-752: Adjust You Account page layout

src/app/home/home.component.html, src/app/home/home.component.scss, src/app/home/home.component.ts
We can handle 1,2, or 3 highlight cards on the homepage. 2 or more use the grid component as in the past, a single card is treated as a special case.
1 card:
2 cards:
3 cards:
6 cards is not supported, but in case it happened this is how it would look:
=> DON-735: Adjust layout for single highlight cards on home page

.circleci/config.yml, src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.scss, src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/validators/validate-billing-post-code.ts
For most errors we ask people to fix them in place before they progress to the next step, but that doesn't work for stripe errors - in that case they need to continue through the form and press the confirm button again.
This reverses some of the work done in DON-493, which I think no longer makes sense now we are confirming payments on the server side only.
Now if you use get a card decline the error looks like this, but it doesn't block you progress through the form and pressing confirm again. You can keep trying as many times as you like until the donation works, which it may do if you add funds to your bank account at the same time:
=> Fix DON-946: Stop stripe blocking retrying donation

src/app/home/home.component.html, src/app/home/home.component.scss, src/assets/images/arrow-next-with-circle.svg, src/assets/images/arrow-prev-with-circle.svg
Rebuilt carousel button SVGs to include circles with shadows, so we can control the position of the arrow within the circle easily.
=> DON-576: Charity carousel amends

package-lock.json, package.json, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/conversionTracking.service.ts, src/app/donation-start/donation-start-container/donation-start-container.component.spec.ts, src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/donation-thanks/donation-thanks.component.spec.ts, src/app/donation-thanks/donation-thanks.component.ts, src/app/donation.service.spec.ts, src/app/donation.service.ts, src/app/identity.service.spec.ts, src/app/identity.service.ts, src/app/login-modal/login-modal.component.spec.ts, src/app/my-account/my-account.component.spec.ts, src/app/register-modal/register-modal.component.spec.ts, src/app/reset-password/reset-password.component.spec.ts, src/app/stripe.service.spec.ts, src/app/transfer-funds/transfer-funds.component.spec.ts, src/app/transfer-funds/transfer-funds.component.ts, src/environments/environment.interface.ts
Intending to remove ngx-matomo because it's not compatible yet with Angular 17
See https://github.com/Arnaud73/ngx-matomo/issues/107 and notes on ticket.
=> DON-950: Replace ngx-matomo library with ngx-matomo-client

server.ts
This appears to have stopped the payment method form loading. Reverts thebiggive/donate-frontend#1545
=> Revert "Try to include the narrowest recaptcha CSP we expect to work"

src/app/app.component.scss
=> Fix DON-972: Detailed cookie choices are hidden behind navigation

src/app/meta-campaign/meta-campaign.component.ts
Throwing an error breaks the page, if there's no fund we don't want to set the specific props yet, but we may need to set them slightly later. Throwing an error broke that.
Changing type of setFundSpecificProps to
`(fund: Fund) => void` so we don't get errors
from calling it without a fund.
=> Fix ticker on fund pages

src/app/donation-start/donation-start-container/donation-start-container.component.ts, src/app/donation-start/donation-start-form/donation-start-form.component.ts
I didn't fully get to the bottom of how the bug was happening, but I did manage to reproduce it reliably.
It seemed like the error message that's displayed "Please enter your billing postcode" may be unrelated to the actual block to progress.
I found that we were calling the stepper.next method at https://github.com/thebiggive/donate-frontend/blob/fc4a02a8469edf57c927d56c8a778dce002e22bf/src/app/donation-start/donation-start-form/donation-start-form.component.ts#L1084 but for some reason the stepper didn't visible advance. I don't know what's going inside the stepper or angular that means that doesn't happen, but refreshing the page fixes it. I tried wrapping the function in ngZone.run in case somehow we were outside a context where Angular could detect changes, but that didn't fix …
=> DON-981: Reload page after login on donation page

src/app/donation-start/donation-start-container/donation-start-container.component.ts, src/app/donation-start/donation-start-form/donation-start-form.component.ts
Reverts thebiggive/donate-frontend#1564
This didn't seem to fix the original problem in testing, and I have been trying my alternative fix approach without it as I branched off older `develop`. That seems to work now on https://github.com/thebiggive/donate-frontend/pull/1565.
=> Revert "DON-981: Reload page after login on donation page"

src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/donation.model.ts, src/app/search.service.ts
At the moment we have a bug where finalising the donation can be blocked when starting a pending donation and then logging in to an account that has donation funds, because we don't allow converting from a card donation to a funds donation.
=> DON-981: Force recreating donation when logging in to account with funds

src/app/app-routing.ts, src/app/campaign.service.ts, src/app/explore/explore.component.html, src/app/explore/explore.component.spec.ts, src/app/explore/explore.component.ts, src/app/explore/explore.module.ts, src/app/highlight-cards-resolver.ts, src/app/highlight-cards/HighlightCard.spec.ts, src/app/highlight-cards/HighlightCard.ts, src/app/highlight-cards/highlight-cards.component.cy.ts, src/app/highlight-cards/highlight-cards.component.html, src/app/highlight-cards/highlight-cards.component.ts, src/app/home/home.component.html, src/app/home/home.component.ts, src/app/home/home.module.ts
There are currently no highlight cards on our staging environment, so I added some hard-coded ones to test this. Kept that part out of the commit of course.
I've coded it to only show the highlight cards on the explore page if there are no more than 6 explore cards, and if there is no search term - I thought probably if someones doing a search then we want to just let them focus on that search. It might be worth also setting to only show the highlight cards if the are no filters turned on.
Also if there are no campaigns found from a search or selected filters (or if we just have no campaigns at all to show) we currently show "We can't find any campaigns matching this search but there are lots more to choose from.". I guess we don't want that at the same time as the highlight cards, but as …
=> Don 713 highlight cards on explore page

server.ts, src/app/campaign-details/campaign-details.component.ts
This does seem to have the downside that the embed won't work on dev workstations, since we are not loading the site with HTTPs there, and fixing that doesn't seem that straightforward. But still should give some privacy improvement, and should work ok in staging etc. Looks like it's not trivial to get HTTPs working in dev: https://stackoverflow.com/questions/39210467/get-angular-cli-to-ng-serve-over-https
=> DON-979: Use no-cookie version of youtube embed

src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.scss
This isn't perfect, because the label is sometimes wider than we would like, so occludes a bit more of the border behind it on the right hand side than the left.  But I think it's probably good enough and it's not worth spending lots of time on trying to possibly make something better. Example of the label being a bit wider than we'd like:
To make it easier to review what we've got here I've made several copies of this donation amount input on the same form showing different length copy. The charity name here is also fictionalised. Of course these changes are not going to be checked into git. Video below to show how this looks over a range of screen widths:
[Screencast from 2024-07-08 10-37-01.webm](https://github.com/thebiggive/donate-frontend/assets/159481/9380e5a2-125f-4b4a-ae47-a5271d8 …
=> DON-976: Allow long charity names to show over donation amount input

src/app/my-regular-giving/my-regular-giving.component.html, src/app/my-regular-giving/my-regular-giving.component.ts
I think this can probably complete the ticket.
Before:
After:
The cards link to the campaign page. At some point before we launch regular giving I think we will probably need to make a dedicated page for viewing each individual agreement with some facilities to manage it (e.g. end the agreement, maybe see a list of donations taken so far and perhaps upcoming in relation to it), so at that point we might link to that instead, and we might add a button to each card.
=> DON-1025: Adjust layout of my regular giving page to use big give cards

src/app/stripe.service.ts
We now only want to setup future usage if the appropriate tick-box is selected by the donor.
=> DON-896: Stop forcing setup_future_usage in payment element setup

src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.ts
Adds some complexity as if the donor declares that they want to claim GA without a tip we now need to forget that declaration if they go back in the form and add a tip
=> DON-1068: Use different GA copy for tip or no tip

src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/environments/environment.staging.ts
Implemented based on pattern of code removed in
https://github.com/thebiggive/donate-frontend/pull/1535
I noticed an existing problem with the "£# donation to support Big Give"
- we were displaying the end of the sentence without the begining if the tip amount form field was invalid (e.g. blank because not yet filled in)
So the logic I have implemented is:
If tip amount is not filled in with a valid value, show nothing
If running A/B test and in variant B and tip amount is filled in with zero show "Even £1 makes a big difference to Big Give"
If not running A/B test or not in variant B show
show "Even £1 makes a big difference to Big Give show "£0 donation to support Big Give" or "£5 donation to support Big Give" etc.
To test variant B in a non-production environment, add …
=> BG2-2739: A/B test adding test for zero tip

src/app/my-account/my-account.component.scss
`flex-start` has wider support, e.g. medium-old Safari
=> Fix flex justify & align compatibility warnings

.circleci/config.yml, Dockerfile, src/app/node-version.spec.mjs
Our existing tests run in the browser. This new test is really static anysis using a test framework, so it needs access to the filesystem which isn't possible in the browser. Hence running it separately, using the node built-in test framework.
=> DON-1073: Add check for consistent node version across ECR and SE

src/app/app-routing.ts, src/app/regular-giving/regular-giving.component.cy.ts, src/app/regular-giving/regular-giving.component.html, src/app/regular-giving/regular-giving.component.scss, src/app/regular-giving/regular-giving.component.ts
URI is `/regular-giving/<campaignID>` e.g. `/regular-giving/a05ds000000x4tRAAQ`
Feature flagged to not be available in production.
Features so far:
- The page can only be viewed by a logged in user. Attempt to access without logging in will trigger a redirect through the login form and back to the page
- Heading shows the name of the campaign and charity
Still required:
Everything else! e.g.
- Return 404 or display error if campaign is not set up for regular giving (see BG2-2711)
- Display campaign details and links in a nice way (probably with a sidebar similar to on donation page)
- Create actual form for donor to fill in details of what they want to give and confirm. Also the form needs to reflect back to them some of their logged in account details so they can make sure they're logged …
=> DON-998: Create mostly page to hold regular giving mandate creation form

src/app/stripe.service.ts
Might swerve edge case bug where a token ends up with no value for future usage, causing server side crashes later. Not tested end to end as I'm not sure exactly when there are issues/ how to repro.
=> Add `setupFutureUsage: 'on_session'` to Stripe element options

.circleci/config.yml
I'm hoping this will allow Jira & Slack post-steps to work again, as both seem to rely on git metadata which is not otherwise needed & so not yet present with the new build approach.
=> Try `checkout` before ECS updates

.circleci/config.yml
Reverts thebiggive/donate-frontend#1697 – possibly implicated in wrong environment deployment steps running
=> Revert "Try `checkout` before ECS updates"

src/app/login/login.component.scss
Fixing issue noted on ticket.
Before
After
=> DON-1072: Add space above friendly captcha widget on login page

tsconfig.app.json, tsconfig.eslint.json
And not main build, which I think has maybe added warnings like "Warning: /home/circleci/******/server.ts is part of the TypeScript compilation but it's unused. Add only entry points to the 'files' or 'include' properties in your tsconfig."
=> Try adding `server.ts` to includes just for linting

src/app/app.component.spec.ts, src/app/campaign-details/campaign-details.component.spec.ts, src/app/charity/charity.component.spec.ts, src/app/donation-start/donation-start-container/donation-start-container.component.spec.ts, src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts, src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.spec.ts, src/app/donation-start/donation-start-login/donation-start-login.component.spec.ts, src/app/donation-thanks/donation-thanks.component.spec.ts, src/app/explore/explore.component.spec.ts, src/app/home/home.component.spec.ts, src/app/login-modal/login-modal.component.spec.ts, src/app/meta-campaign/meta-campaign.component.spec.ts, src/app/popup-standalone/popup-standalone.component.spec.ts, src/app/reset-password/reset-password.component.spec.ts, src/app/time-left.pipe.spec.ts, src/app/transfer-funds/transfer-funds.component.spec.ts, src/app/update-card-modal/update-card-modal.component.spec.ts
Before this change we had many hundreds of lines of errors showing up, as we ran tests, e.g.:
ERROR: 'NG0304: 'swiper-slide' is not a known element (used in the 'HomeComponent' component template):
1. If 'swiper-slide' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
2. If 'swiper-slide' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
and
ERROR: 'NG0303: Can't bind to 'logo' since it isn't a known property of 'biggive-hero-image' (used in the 'MetaCampaignComponent' component template).
1. If 'biggive-hero-image' is an Angular component and it has the 'logo' input, then verify that it is a part of an @NgModule where this component is declared.
2. If …
=> Stop many error messages showing up `npm run ci output`

src/assets/scss/_mat-theme.scss
Further reduces `npm run ci` output length from 1,115 lines down to 248 lines.
=> Duplicate files suppress warnings

server.ts
"Content-Security-Policy got directive value `self` which should be single-quoted and changed to `'self'`. This will be an error in future versions of Helmet." and wasm-unsafe-eval equivalent
=> Fix CSP warnings on start

server.ts
Reverts thebiggive/donate-frontend#1744
This did unsurprisingly stop friendly captcha working:
=> Revert "DON-1080: Temporarily remove security clearance for friendly-captcha …"

src/app/meta-campaign/meta-campaign.component.ts
On next deploy to prod after merging this page at https://donate.biggive.org/christmas-challenge-2024 will change from
to something much more like what we have on staging for WMGF:
=> COM-102: Opt-in CC24 in prod for rectangular hero image

src/app/transfer-funds/transfer-funds.component.html, src/app/transfer-funds/transfer-funds.component.ts
Only tangentially related to the ticket but as we're looking at this form to QA it seems like we may as well make these improvements
- Adjusted error copy to account for possible error of using a non-whole number of pounds. Potentially we could do a smallish amount of extra work to show the specific error in each case, but I don't think we need to now. We could also show the min and max amount at all times on the form as part of the instructions instead of only as an error but again that's a bigger change.
- Adjusted form components to only update on blur instead of in real time as the user types. This means the validation error message will only appear when they blur the input, which is quite a bit more user friendly. See https://ux.stackexchange.com/questions/48268/validate-on-blur-or-ke …
=> DON-1085: Improve validation UX in donation funds form

src/app/campaign-details/campaign-details.component.ts
Another possibly better way to do might be using our video component as we do on other parts of the site, but I was in a mood for a quick small change rather than finding the best solution.
=> DON-1089: Add do not track param for vimeo embed on campaign detail page

src/app/donation-start/donation-start-form/donation-start-form.component.html
Adds copy like the example shown below on my local.
Personally I think it looks a bit cramped, but this is the most consistent appearance vs. other copy we put in similar places so probably the safest option for now.
=> DON-1070 – add post-script copy when `optInCharityEmail` choice is Yes

src/app/campaign-details/campaign-details.component.ts, src/app/explore/explore.component.ts, src/app/meta-campaign/meta-campaign.component.html, src/app/meta-campaign/meta-campaign.component.ts
* [give post-search scroll position change enough time to go to the right place](https://github.com/thebiggive/donate-frontend/commit/f47a4cb6747f02ec616db2bc6d459680749b57ad)
* [fix no-op navigation with scroll position impact](https://github.com/thebiggive/donate-frontend/commit/bb8e7363f37b6f121bb7461c904d8c4ccf5cf703)
=> DON-1092 – refine post-search scroll behaviour

src/app/highlight-cards/HighlightCard.spec.ts, src/app/highlight-cards/HighlightCard.ts
The implementation we have of this at the moment is specific to 2024
=> BG2-2775: Don't adjust CC URL after start of Feb 2025

src/app/donation.model.ts, src/app/my-donations/my-donations.component.html, src/app/my-donations/my-donations.component.scss, src/app/my-donations/my-donations.component.ts, src/app/regular-giving/regular-giving.component.ts
Screenshot to show how this would look with one regular donation and one ad-hoc donation side by side:
=> DON-1066: Link to regular giving agreement from card payment

src/app/my-regular-giving/my-regular-giving.component.html, src/app/regular-giving/regular-giving.component.ts
=> DON-998: view mandate link

src/app/my-donations/my-donations.component.html, src/app/my-donations/my-donations.component.scss
As requested in recent comment on ticket
The donation.mandate.activeFrom property is now unused - so we could optimise by removing it and not making matchbot fetch that data, but I think it's OK to leave for now.
=> DON-1066: Move mandate link on donation to bottom-right of card

src/app/app-routing.ts
In all cases where Identity local tokens are needed, pass the decision to the browser
=> Be consistent about SSR `canActivate` route guards

src/app/donor-account.service.ts, src/app/transfer-funds/transfer-funds.component.ts
We can now rely on these accounts being created via the Identity service
=> MAT-379: Stop directly creating matchbot donor accounts

src/app/explore/explore.component.html, src/app/explore/explore.component.ts, src/app/navigation.service.ts
Only a few adjustments to the existing meta-campaign page for the regular giving case.  Specifically removing the ticker, removing the match Funds Remaining indication on each card, changing "Donate now" to "Donate monthly", and changing the "find out more" link target.
This is how it looks with our test campaign. (I added a banner from unsplash & a definition from OED):
I think as it doesn't have those changes we'll also need to either exclude regular giving campaigns from the general explore page, or (IMHO less likely what we want) allow that page to show a mix of regular giving and ad-hoc giving campaigns.
=> Meta campaign page for regular giving

src/app/mandate/mandate.component.html, src/app/mandate/mandate.component.scss
Use elements in a more accessible way (see https://webaim.org/techniques/tables/data) and add a couple of IDs for easier cross-browser use of data in automated tests
=> DON-998 – regular giving receipt table a11y & ID tweaks

src/app/highlight-cards/HighlightCard.spec.ts, src/app/highlight-cards/HighlightCard.ts
Logic for highlight cards should be consolidated inside SF once again
Before:
After:
=> BG2-2776: Remove special priorty handling for CC highlight card

src/app/campaign-details/campaign-details.component.html, src/app/campaign-info/campaign-info.component.html, src/app/campaign.model.ts
We're not expecting these to be filled in for regular giving campaigns, so we don't want to show headings for empty sections on a page.
Similarly for categories and beneficiaries, we shouldn't show the heading if there is no data recorded.
Before:
After:
=> DON-1115: Remove blank campaign info page sections

src/app/exact-currency.pipe.ts, src/app/mandate.model.ts, src/app/mandate/mandate.component.html, src/app/mandate/mandate.component.ts, src/app/money.pipe.ts
In principle has to wait behind
https://github.com/thebiggive/matchbot/pull/1200 although since regular giving isn't possible yet on prod the prod deployment order doesn't matter.
=> DON-1008: Show gift aid amount on regular giving mandate viewing page

src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/regular-giving/regular-giving.component.ts
Clicking these from regests is not working at present - not sure why not but the code to click them is quite brittle, relying on numeric element identifiers. See https://github.com/thebiggive/regression-tests/blob/eb0748213d1682dde8449b1c78dedaf8f0f86f5a/pages/DonateStartPage.js#L37
=> REG-39: Don't require marketing choices in regtest env

src/app/explore/explore.component.html
Previously removed in https://github.com/thebiggive/donate-frontend/pull/1819
=> DON-999: Restore ticker for metacampaign page

src/app/all-active-mandates.resolver.ts, src/app/app-routing.ts
As found by by Dom and noted on ticket.
This resolver is simple enough that I think it's fine inline in app-routing.ts, but I wanted to check whether we're still able to use ResolveFn and inject with a resolver defined in a separate module. Looks like we can.
=> DON-1102: Fix breakage at /my-account/regular-giving

src/app/bodyStyle.ts, src/app/cancel-mandate/cancel-mandate.component.ts, src/app/login/login.component.ts, src/app/mandate.model.ts, src/app/mandate/mandate.component.html, src/app/mandate/mandate.component.scss, src/app/mandate/mandate.component.ts, src/app/my-regular-giving/my-regular-giving.component.html, src/app/my-regular-giving/my-regular-giving.component.scss, src/app/register/register.component.ts
AFAIK this does everything we need in FE about cancelled & cancelling mandates:
- Adds a link from mandate detail / thanks page to cancellation form (if not already cancelled)
- Adds the cancellation date to the donation schedule on the donation detail/thanks page
- Adds a cancelled heading on the mandate detail page
- Adds a grey background for a cancelled mandate on the detail page
- Adds a cancelled heading in the mandate box on the list of mandates page
- Adds the cancellation date in the mandates box on the list of mandates page
- Removes the next payment date on the list of mandates page when n/a
- Auto redirects from the cancellation form back to mandate detail if donor navigates to form for an already-cancelled mandate
=> DON-1022: Mandate cancellation tweaks

src/app/mandate/mandate.component.ts
It's already working fine in local, but on staging it currently links to e.g. /d/my-account/regular-giving/3668e4bc-efac-11ef-bdbd-437378181d17/cancel
It should be without the /d at the start
=> DON-1022: Attempt fix broken for mandate cancellation

src/app/mandate/mandate.component.html, src/app/mandate/mandate.component.scss, src/app/mandate/mandate.component.ts
As discussed today on Slack #develop
Before:
(but clicking the links doesn't work because we never programmed them to share anything specific)
After:
=> Remove non-working social share links from Mandate view page

src/app/regular-giving/regular-giving.component.html, src/app/regular-giving/regular-giving.component.ts
Not sure if the copy is exactly right - the "Please tick the box to confirm" message makes sense for adults who didn't notice the form but maybe isn't right for children who didn't tick the box. Doesn't make sense to ask them to wait years and come back though.
=> DON-1121: Add age confirmation checkbox

src/app/campaign.resolver.ts
May help rule this out as a source of CORS header confusion
=> DON-1125 – explicitly key campaign resolver state separately for browser vs. server

src/app/Money.ts, src/app/backendError.ts, src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.scss, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/donation-thanks/donation-thanks.component.ts, src/app/donation.model.ts, src/app/mandate.model.ts, src/app/money.pipe.ts, src/app/regular-giving/regular-giving.component.html, src/app/regular-giving/regular-giving.component.scss, src/app/regular-giving/regular-giving.component.spec.ts, src/app/regular-giving/regular-giving.component.ts, src/app/transfer-funds/transfer-funds.component.ts, src/assets/scss/donation-common.scss
Two additions to the regular giving form - both copied from and sharing styling with the ad-hoc giving form:
Green match funds available highlight at the top:
Amounts summary table immediately before the confirmation button at the end:
=> Don 1122 know that donations will be matched

src/app/donation-start/donation-start-form/donation-start-form.component.ts
Unless we want to make changes in matchbot as well we need to abandon this donation and create a new one to allow the donor to try using a different card.
Attemping to confirm a donation a second time after 3DS authentication has been attempted leads to Stripe throwing this exception at matchbot:
InvalidRequestException: This PaymentIntent's capture_method could not be
updated because it has a status of requires_action. You may only update the
capture_method of a PaymentIntent with one of the following statuses:
requires_payment_method, requires_confirmation.
=> MAT-409: Cancel donation on failed card 3DS authentication

src/app/app-routing.ts, src/app/donation-thanks/donation-thanks-set-password-dialog.html, src/app/email-verification-token.resolver.ts, src/app/identity.service.ts, src/app/register/register.component.html, src/app/register/register.component.scss, src/app/register/register.component.ts
The plan is they will click a link in the donation thanks email (link generation not yet implemented) to a URI that includes the six digit secret token and their identity UUID, e.g.
/register?c=019816&u=1f0161fa-63ea-6fa8-888d-b1edd20e1c85
Donate then queries the identity backend for the details of the person, and displays in the registration form as implemented in this commit.
The next step is to create a route in identity to allow registration to be done using those details plus the newly chosen password, and implement calling that route here.
=> ID-47: Allow donor to view post-donation registration form

src/app/donation-thanks/donation-thanks-set-password-dialog.component.ts, src/app/donation-thanks/donation-thanks.component.ts, src/app/featureFlags.ts
Technically we should wait until the matchbot PR is merged but it's OK to have this slight breakage in dev only.
Thank you page without set password prompt:
We could replace the prompt with something saying look at your email for a way to set a password, but I think that overcomplicates the thanks page and we don't need it.
=> ID-47: Stop offering new accounts post donation in dev env

src/app/campaign-list.resolver.ts, src/app/campaign-stats-resolver.ts, src/app/campaign.resolver.ts, src/app/explore/explore.component.ts, src/app/highlight-cards-resolver.ts, src/app/logCalloutError.ts, src/app/logCampaignCalloutError.ts
Give them their own group, to separate from `donate_error`s easily, and a less misleading identifier intro
=> Tweak callout logs

src/app/campaign-stats.model.ts, src/app/donation-created-response.model.ts, src/app/donation.service.spec.ts, src/app/fundingInstruction.model.ts
Other than in one test these were never used as values, only as types.
=> Convert remaining model classes to types

src/app/highlight-cards/HighlightCard.ts
This reverts commit 23451e9650c18007ea47b31ad92c220f1bfed3f7.
Was only intended for use during GMF live period
=> Revert "Move GMF highlight card to start of list"

src/app/stripe.service.ts
We've tested the new behaviour in staging, so may now be ready to update the prod behaviour.
=> MAT-390 part 1: Stop overiding donor save card choice in prod

eslint.config.mjs
https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/docs/rules/no-positive-tabindex.md
From MDN:
> Warning: You are recommended to only use 0 and -1 as tabindex values.
>
> Avoid using tabindex values greater than 0 and CSS properties that can
> change the order of focusable HTML elements (Ordering flex items). Doing
> so makes it difficult for people who rely on using keyboard for
> navigation or assistive technology to navigate and operate page content.
>
> Instead, write the document with the elements in a logical sequence.
=> DON-521: Add eslint rule 'no-positive-tabindex'

.git-blame-ignore-revs, src/BigGiveTitleStrategy.ts, src/app/app-routing.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/explore/explore.component.ts, src/app/home/home.component.ts, src/app/mandate/mandate.component.ts, src/app/page-meta.service.ts, src/app/stripe.service.ts, src/environments/common.ts
Previously a few pages (e.g. http://localhost:4200/transfer-funds and http://localhost:4200/explore ) did not set specific titles so we just showed 'Big Give' which is unhelpful in a list of tabs.
This commit makes sure every component has a title, and that the entry in our routes array explicitly declares a title entry (although it may be undefined) for every route.
=> Don 521 a11y improvements

src/app/campaign-details/campaign-details.component.html, src/app/explore/explore.component.html, src/app/login-modal/login-modal.html, src/app/login/login.component.html, src/app/transfer-funds/transfer-funds.component.html
I a couple of these and found it was a real issue that the link were not focusable with the tab key and not clickable with enter key. Fixed here.
Not sure if there's any more direct way to tell angular to make an `a` act like a link, I don't love the href attribute with no value but as we have eslint to remind us to put it in where needed it's OK.
The original sin might be HTML using the same element for links and link targets.
=> DON-521: Fix links not keyboard focusable/clickable

src/app/campaign-details/campaign-details.component.html, src/app/campaign-details/campaign-details.component.ts, src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/explore/explore.component.html, src/app/explore/explore.component.ts, src/app/login-modal/login-modal.component.ts, src/app/login-modal/login-modal.html, src/app/login/login.component.html, src/app/transfer-funds/transfer-funds.component.html, src/app/transfer-funds/transfer-funds.component.ts
Adding href to these links in #1977 made them available to be used by keyboard, but also broke them since the href didn't point to any sensible place. Added a call to `Event.preventDefault()` for each one. Not sure if there might be any more elegant way to do this but this does seem to work fine when I test on local.
Also added a feature to dismiss the dubug info box on donation form, e.g. in case it gets in the way when wanting to make a screenshot. (Actually it was in adding that feature that I found all these links are broken)
I did a search for regex `href.*click` to see which lines needed editing
=> DON-521: Fix broken links introduced in recent accessability fix

src/app/app-routing.ts, src/app/app.module.ts, src/app/campaign.resolver.ts, src/app/campaign.service.spec.ts, src/app/campaign.service.ts, src/app/donation-thanks/donation-thanks.component.ts, src/app/donation.service.spec.ts, src/app/donation.service.ts, src/app/donor-account.service.ts, src/app/featureFlags.ts, src/app/fund.service.spec.ts, src/app/fund.service.ts, src/app/regularGiving.service.ts, src/app/transfer-funds/transfer-funds.component.ts, src/environments/environment.interface.ts, src/environments/environment.production.ts, src/environments/environment.regression.ts, src/environments/environment.staging.ts, src/environments/environment.ts, src/server.ts
FE (and readers of its code) should know when its talking to SF and when its not, since that is about to change.
=> MAT-411: Use matchbot campaign api instead of salesforce to load donate pages in dev env

src/app/campaign.model.ts, src/app/donation-start/donation-start-container/donation-start-container.component.html, src/app/donation-start/donation-start-container/donation-start-container.component.ts, src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.ts
Should help us see what needs to be fixed to get matchbot campaign API compatible as a replacement for salesforce API, including testing against several different campaigns in staging.
Also moved the existing "debug info" developer panel on donate page to the sidebar so it stops being in the way of the actual donation form. Maybe now its dismiss function is unecassary but I've left it, I guess useful if we want to take a screenshot without showing this.
=> MAT-411: Display campaign errors on donation page

src/app/featureFlags.ts
For now matchbot simply proxies data in real time from SF as long as SF is up and has the campaign, and sends a reconstruction of the same saved date if SF is down, but this should change very soon and matchbot will be the source of aggregated donation data such as total amount raised per campaign.
=> MAT-411: Use new matchbot campaign API in all environments

src/app/identity.service.ts
I think the new version has been supported in Production for a long time, so we can simplify Identity if we switch this call over.
=> Remove trailing '/' when making email verification token

src/app/regular-giving/regular-giving.component.html, src/app/regular-giving/regular-giving.component.ts
I think a checkbox inside a list doesn't really work well, so it makes more sense to make the two checkboxes (aged over 18 and making unmatched donation) sit together one after the other, and just use normal running copy to describe the error.
Also making the error appear and disappear reactively when the donation amount is reduced above or below the matchable maximum, and when unmatched option is clicked.
=> DON-1134: Improve UI for making unmatched regular giving donation

src/app/donation-start/donation-start-form/donation-start-form.component.html, src/app/donation-start/donation-start-form/donation-start-form.component.scss, src/app/regular-giving/regular-giving.component.html, src/assets/scss/donation-common.scss
We had a mix of full width and 40% width buttons - making them all 40% width.
There's potential to refactor to reduce the duplication but not necassarily right now.
=> DON-1150: Reduce two buttons in regular giving stepper to 40% width

src/app/explore/meta-campaign-banner/meta-campaign-banner.component.scss
Letting the image grow much beyond 2,000px wide is a problem on big screens because then it becomes to tall and the bottom gets cropped off as the height is fixed at 600px
=> DON-1120: Limit new banner image width to 2,000px

src/app/home/home.component.html
Before:
After:
As requested by Alex via @BethBigGive
=> New homepage content

src/app/campaign-info/campaign-info.component.html, src/app/campaign-info/campaign-info.component.ts, src/app/campaign.model.ts, src/app/campaign.service.spec.ts, src/app/campaign.service.ts, src/app/donation-start/donation-start-container/donation-start-container.component.spec.ts
The "7 donations" shown here in prod is currently the count from the parent campaign which is not at all clear. This PR replaces it with the count of the charity campaign, which in this case would be zero.
=> Don 1107 individual donation count

src/app/donation-start/donation-start-form/donation-start-form.component.ts, src/app/donation.model.ts, src/app/donation.service.ts, src/app/my-donations/my-donations.component.ts
Adding apple pay and also google pay and also (string & {}) in case there's anything else we missed. `(string & {})` is effectively the same as string but adding the {} part of it prevents typescript from simplifying the union, so we can see tha tthe type is any of various known methods, plus any other possible method according to stripe config.
=> MAT-429: Expand static types to better reflect dynamic reality + allow resuming wallet paymeent donations

src/server.ts
I'd like to see the sitemap link from robots.txt working once in staging, then will merge this.
=> DON-984: Don't serve sitemap outside prod

Dockerfile, src/index.html, src/index.production.html, src/index.regression.html, src/index.staging.html
For now keeping the four files and copying new content into each one. It might be worth reducing it down to four files and just running a script to do specific replacements within the file for the parts that differ per environment.
Also kept the script to write the git commit ID into each file for now so I can see when it deploys. Can remove after I've seen it working but I think it might be worthwhile to have it to see easily what commit is deployed to each env, although it doesn't need to be in index.html necessarily - maybe worth making another file just for that so we could go e.g. donate.biggive.org/colophon and and that could be a page giving details including the git commit ID and timestamp.
=> DON-1142: Fix browser detection in index file for all environments

src/index.html, src/index.production.html, src/index.regression.html, src/index.staging.html
Sharing this as a draft PR since I found it uncommitted, but not realising its probably not needed since we can use remote chrome inspector to override this check anyway to see whether its blocking access to the site from devices that could actually make use of it.
=> DON-1142: Allow skipping outside-angular browser-compat-check

src/app/campaign-details/campaign-details.component.html, src/app/campaign.model.ts
(We know it won't be present currently as we don't offer a way for charities to enter it, but hoping to implement that soon)
=> BG2-2892: Output alt-text on campaign additional images if present

src/app/donation-start/donation-start-form/donation-start-form.component.ts
Marking this as readonly just prevents TS from auto-widening the type and so lets us see what the numbers are e.g. when we hover on references to `this.tipPercentageDefaults`
=> BG2-2972: Refactor, narrow tip percentage default type
