- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.spec.ts
- src/app/app.module.ts
- src/app/campaign-card/campaign-card.component.html
- src/app/campaign-card/campaign-card.component.scss
- src/app/campaign-card/campaign-card.component.spec.ts
- src/app/campaign-card/campaign-card.component.ts
- src/app/campaign-summary.model.ts
- src/app/search-results/search-results.component.html
- src/app/search-results/search-results.component.scss
- src/app/search-results/search-results.component.spec.ts
- src/app/search-results/search-results.component.ts
* Use Angular Material grid list for results.
* Also add model support for campaign dates, added in updated
[v1.0.1 of the Campaign API contract](https://app.swaggerhub.com/apis/Noel/TBG-Campaigns/1.0.1)
> DON-31 - add campaign result cards

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
These were initially set to a fixed charity for the first donation page demo.
> Make target charity & match status dynamic

- src/app/app.component.spec.ts
- src/app/app.module.ts
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign.model.ts
- src/app/campaign.service.spec.ts
- src/app/charity-checkout-donation.model.ts
- src/app/charity-checkout.service.ts
- src/app/donation-start/donation-start-match-confirm-dialog.component.ts
- src/app/donation-start/donation-start-match-confirm-dialog.html
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
- src/app/time-left.pipe.spec.ts
- src/app/time-left.pipe.ts
* DON-5 - fix days left outputs with a custom pipe
* DON-8 - limited / depleted match funds warnings: Check the matching reserved amount after a donation to a matched campaign is initialised. Warn the donor and get confirmation before proceeding if full match funds to cover their donation are unavailable.
> DON-5, DON-8 - indicate match status; fix days left counts

- src/app/meta-campaign/meta-campaign.component.html
- src/app/meta-campaign/meta-campaign.component.spec.ts
Show time left to the meta-campaign's start date if in Preview, or its total amount raised otherwise.
> DON-27, DON-28 - add meta-campaign subtitles

- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign.model.ts
- src/app/campaign.service.spec.ts
- src/app/meta-campaign/meta-campaign.component.spec.ts
- DON-38 include new alternative fund use field in campaign details view
> DON-38 include new alternative fund use field in campaign details view

- src/app/campaign-details/campaign-details.component.html
- DON-19 + DON-20 show quotes and budget details
> DON-19 + DON-20 show quotes and budget details

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/campaign-card/campaign-card.component.html
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.spec.ts
- DON-17-DON-26 Display campaign additional images on carousel
> DON-17-DON-26 Display campaign additional images on carousel

- package-lock.json
- package.json
- server.ts
- src/app/campaign.service.spec.ts
- src/app/meta-campaign/meta-campaign.component.ts
- src/app/search-results/search-results.component.ts
* Fix `window` logic with Server-Side Rendering (for real)
* Add Node/Express access logs
* Update `handlebars` to new secure version
> Fix `window` logic with Server-Side Rendering + add access logs + update lib

- .circleci/config.yml
- README.md
> Develop -> master

- src/app/app.module.ts
- src/app/donation-start/donation-start-error-dialog.component.ts
- src/app/donation-start/donation-start-error-dialog.html
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- src/app/donation.service.ts
Also improve logic around locally saved data about donations which
are cancelled, and auto-cancel any found when coming back from
a Charity Checkout error.
> DON-42 - handle Charity Checkout errors better

- src/index.html
- src/index.production.html
- src/index.staging.html
- src/polyfills.ts
* Hopefully get polyfills needed for IE11 to run the app
* Try to warn off older IEs in an IE10-compatible way
> DON-34 - Internet Explorer fix attempts

- src/app/campaign-details/campaign-details.component.ts
- src/app/donation-start/donation-start.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
- src/app/page-meta.service.spec.ts
- src/app/page-meta.service.ts
Also abstract out common metadata properties so all components
set the same keys consistently.
> DON-81, DON-82 - add more sharing metadata

- src/app/app.module.ts
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.ts
- src/main.ts
Fix carousel crashing server-rendered `CampaignDetailsComponent`
> DON-84 - carousel SSR workaround

- src/app/meta-campaign/meta-campaign.component.html
Render element with width 100px for sharp rendering
on high-DPI screens.
> DON-75 - request logos at max 200px size

- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation.service.ts
Also update local donation copy so it's not incorrectly offered for reuse
> DON-89 - add details to 'thank you' receipt

- src/app/campaign-card/campaign-card.component.ts
- src/app/campaign-details-card/campaign-details-card.component.html
- src/app/campaign-details-card/campaign-details-card.component.spec.ts
- src/app/campaign-details-card/campaign-details-card.component.ts
Also tidy up donation count display
> DON-49 - show real raised percentage

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.scss
- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign-details/campaign-details.component.ts
- src/main.ts
* Drop carousel in favour of correctly scaled images all on overview
* Give video row more space
> DON-100 - image & video layout

- src/app/campaign-card/campaign-card.component.html
- src/app/campaign-card/campaign-card.component.scss
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.scss
- src/app/meta-campaign/meta-campaign.component.ts
* DON-105 - tidy up lists in campaign details
* DON-108 - preserve charities' line breaks in more campaign detail content
* DON-112 - make titles in campaign cards links through to more info
> DON-105, DON-108, DON-112 UX / layout tweaks

- src/app/app.module.ts
- src/app/charity-checkout-donation.model.spec.ts
- src/app/donation-complete/donation-complete.component.spec.ts
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
- src/app/donation.model.ts
- src/app/donation.service.spec.ts
- src/app/donation.service.ts
Always consult the latest storage value instead of maintaining per-app copies in memory, so data doesn't get mixed up if the app's used in multiple tabs
> DON-104 - smarter use of local storage + model refactor

- src/app/app.module.ts
- src/app/app.server.module.ts
- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign-details/campaign-details.component.ts
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
- src/app/meta-campaign/meta-campaign.component.spec.ts
- src/app/meta-campaign/meta-campaign.component.ts
On the three main pages which can benefit from this, finish following the data handover approach detailed in https://medium.com/@evertonrobertoauler/angular-5-universal-with-transfer-state-using-angular-cli-19fe1e1d352c
This makes page loading smoother and eliminates unnecessary extra client-side HTTP calls
> DON-119 - transfer server state to the client

- src/app/campaign-details/campaign-details.component.html
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
- src/app/filters/filters.component.html
- src/app/filters/filters.component.ts
Quick changes discussed with Jonathan this morning:
* Meta-campaign: Tweak filter copy & move UK to the top
* Campaign detail: Move budget detail to same line as amount
* Donation start: Take out campaign summary so donors reach the form earlier
> Minor UX tweaks

- src/app/filters/filters.component.html
- src/app/filters/filters.component.scss
This should make it more obvious that more are available on at least some mobile breakpoints
> DON-135 - add a basic 'fade out' for filter bar

- src/app/donation-start/donation-start.component.scss
- Increase form field font size and max width
> DON-128 - Increase form field font size and max width

- src/app/hero/hero.component.html
- src/app/hero/hero.component.scss
- src/app/hero/hero.component.ts
- src/app/meta-campaign/meta-campaign.component.html
Reduce large heading copy and prepare for shorter champion logos to work on the fund-specific meta-campaign view.
> DON-123 - improve champion logo display

- src/app/filters/filters.component.scss
See https://github.com/Compass/compass/issues/2010
> DON-135 - work around Safari treating 'transparent' as a fade from black

- src/app/app-routing.module.ts
See https://stackoverflow.com/a/44372167/2803757
> DON-144 - maintain expected scroll positions

- src/app/donation-complete/donation-complete.component.html
- src/app/navigation/navigation.component.html
- DON-109 Make tbg logo link to homepage
> DON-109 Make tbg logo link to homepage

- src/app/campaign-search-form/campaign-search-form.component.spec.ts
- src/app/campaign-search-form/campaign-search-form.component.ts
- src/app/filters/filters.component.html
- src/app/filters/filters.component.spec.ts
- src/app/filters/filters.component.ts
- src/app/hero/hero.component.html
- src/app/hero/hero.component.spec.ts
- src/app/hero/hero.component.ts
- src/app/meta-campaign/meta-campaign.component.html
- src/app/meta-campaign/meta-campaign.component.scss
- src/app/meta-campaign/meta-campaign.component.spec.ts
- src/app/meta-campaign/meta-campaign.component.ts
- src/styles.scss
* DON-121 - add a no results message and reset functionality
* DON-127 - clear results and show loading indicator, on update
> DON-121, DON-127 - search enhancements

- src/environments/environment.production.ts
To merge ~7am 28 November to coincide(ish) with Charity Checkout's switch over.
> Switch Production to MatchBot

- src/app/analytics.service.ts
See https://stackoverflow.com/a/57928460/2803757
> DON-138 - fix GA event value tracking

- src/app/ticker/ticker.component.html
- src/app/ticker/ticker.component.scss
- src/app/ticker/ticker.component.ts
- src/app/time-left.pipe.spec.ts
- src/app/time-left.pipe.ts
* DON-151 - show time remaining in ticker while live and duration only when not
* DON-155 - make all uses of `timeLeft` pipe auto-update themselves once a second
> DON-151, DON-155 - ticker / pipe enhancements

- src/app/time-left.pipe.spec.ts
- src/app/time-left.pipe.ts
Shortening these so all units look good in the campaign detail page cards
> DON-163 - abbreviate mins and secs

- src/app/ticker/ticker.component.scss
- src/app/ticker/ticker.component.ts
- src/app/time-left.pipe.spec.ts
- src/app/time-left.pipe.ts
Rolling back changes to fix SSR
> DON-151, DON-155 revert

- src/app/campaign-card/campaign-card.component.html
- src/app/campaign-details/campaign-details.component.html
- src/app/donation-complete/donation-complete.component.html
- src/app/donation-start/donation-start.component.html
- src/app/navigation/navigation.component.html
* semantic HTML: make links act like links
* send TBG logo links back to the Donate app's home
> DON-165 - link fixes

- src/assets/scss/_mat-theme.scss
This was a regression from more selective Material theming rolled out this morning
> DON-172 - fix invisible loading spinners

- src/app/campaign-search-form/campaign-search-form.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
* fix enter to search on first attempt
* fix sort options when search term's been cleared
> DON-174 - search form tweaks

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
* Accept '.00' after main amount
* Show a validation message next to the Donate button if it's greyed out
> DON-178 - improve donation amount validation

- src/app/explore/explore.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
* DON-182 - sort by Most Raised after master campaign closes
* DON-184 - fix blank term detection
> DON-182, DON-184 default result orders

- src/app/footer/footer.component.html
- src/app/navigation/navigation.component.html
- DON-187 update nav bar + footer
> DON-187 update nav bar + footer

- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign.model.ts
- src/app/campaign.service.spec.ts
- src/app/donation-start/donation-start-match-confirm-dialog.html
- src/app/donation-start/donation-start.component.ts
- src/app/hero/hero.component.spec.ts
- src/app/ticker/ticker.component.spec.ts
- DON-118 Include new surplus info copy in popup modal
> DON-118 Include new surplus info copy in popup modal

- src/app/campaign-card/campaign-card.component.html
- src/app/campaign-card/campaign-card.component.ts
- src/app/campaign-details-card/campaign-details-card.component.html
- src/app/campaign-details-card/campaign-details-card.component.ts
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.ts
- src/app/hero/hero.component.html
- src/app/hero/hero.component.ts
- src/app/image.service.spec.ts
- src/app/image.service.ts
Plus standardise and tidy up how we request images scaled to
non-original dimensions
> DON-188 - dynamically request webp images where appropriate

- src/environments/environment.regression.ts
This needs the MatchBot / infrastructure changes to be reviewed and regression env MatchBot deployed and running correctly first
> MAT-67 - have regression env use MatchBot

- src/app/donation-start/donation-start.component.html
- DON-195 tipping info section
> DON-195 tipping info section

- src/app/donation-start/donation-start.component.html
> DON-196 - Tipping copy tweak

- src/app/hero/hero.component.html
- src/app/meta-campaign/meta-campaign.component.html
This is a minor template tidying tweak I realised we can make after making the key change for DON-198.
It has no user-facing impact and can be merged after the COVID-19 appeal launch. Marking WIP for now.
> DON-198 - improve `*ngIf` conditions' readability

- src/app/ticker/ticker.component.html
Make it explicit that the values here include Gift Aid
> DON-200 - clearer ticker grand total copy

- src/app/campaign-details-card/campaign-details-card.component.html
- src/app/campaign-details-card/campaign-details-card.component.ts
- DON-19 temporary campaign target logic
> DON-19 temporary campaign target logic

- src/app/navigation/navigation.component.html
- DON-202 Add close action when clicking on explore campaigns in mobile
> DON-202 Add close action when clicking on explore campaigns in mobile view

- src/app/campaign-card/campaign-card.component.html
- DON-203 always show total funds raised regardless matched or not
> DON-203 always show total funds raised regardless matched or not

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- DON-205 remove covid19 donation limit + leave in abstract control for dynamic max amount validation
> DON-205 remove covid19 donation limit

- src/app/campaign-details-card/campaign-details-card.component.html
- src/app/campaign-details-card/campaign-details-card.component.ts
Revert "DON-201 temporary campaign target logic"
This reverts commit 480dbd1479cf061ed37d5728379b29ae0cf00e79.
> DON-206 Revert don201 campaign target

- package-lock.json
- package.json
- src/app/app.component.ts
- src/app/app.module.ts
- src/styles.scss
This approach brings detection to the
actual app component render and should not
crash server-side rendering
> DON-194 – Switch method of awaiting icon font

- src/app/app.component.ts
- src/styles.scss
* remove hard dependency on `document` which doesn't exist on the server
* hide the `AppComponent` instead of the `body`
* immediately add visible class for server render, waiting client-side
> DON-194 - fix SSR runtime crash w/ icon blip fix

- src/app/app.module.ts
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.scss
- src/app/campaign-details/campaign-details.component.ts
* make message more prominent
* add icons + titles which show past/future status at a glance
> DON-219 - improved closed campaign messaging

- src/app/donation-start/donation-start.component.html
- DON-224 gift aid yes copy tweak
> DON-224 gift aid yes copy tweak

- src/app/donation-start/donation-start.component.html
- DON-239 update gift aid copy
> DON-239 update gift aid copy

- src/app/hero/hero.component.html
- src/app/meta-campaign/meta-campaign.component.html
-DON-243 hide search and filters component when less than 10 participating charities
> DON-243 hide search and filters component when less than 10 participating charities

- src/app/campaign-details/campaign-details.component.html
- src/app/donation-start/donation-start.component.html
- src/app/footer/footer.component.html
Also use better wording for closed campaigns
> DON-250 - pin Date pipe outputs to UK timezone

- src/app/charity-checkout-donation.model.spec.ts
- src/app/charity-checkout-donation.model.ts
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
- src/app/donation-start/donation-start.component.ts
- src/app/stripe.service.ts
* scroll to errors
* add errors for missing radios
Branched from DON-230 in error -> please review https://github.com/thebiggive/donate-frontend/pull/298 first.
> DON-258 – validation improvements

- src/app/donation-start/donation-start.component.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
> DON-230 - move reservationMinutes to environment config

- src/app/donation-start/donation-start.component.ts
Thunk should now work in both the types of scenario
in which it is used again. Also expanded docs to make
it explicit what it's handling and why.
> DON-262 - fix continuing donations

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
Also fix DON-262 behaviour after cancelling an offered existing donation.
> DON-258, DON-259 - step scrolling fixes

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- src/app/donation.model.ts
Also fix setting `giftAid` early
> DON-232 - fix handling of £ in tip amount

- src/app/donation-start/donation-start.component.ts
- DON-230 check whether a donation is re-used or cancelled before creating a new one
> DON-230 fix re-usable donation reservation timer

- src/app/donation-start/donation-start.component.ts
- DON-268 double check amount is greater than 0 before creating
> DON-268 double check amount is greater than 0 before creating

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/campaign-card/campaign-card.component.html
- src/app/campaign-card/campaign-card.component.scss
- src/app/campaign.service.ts
- src/app/charity-campaigns.resolver.ts
- src/app/charity/charity.component.html
- src/app/charity/charity.component.scss
- src/app/charity/charity.component.spec.ts
- src/app/charity/charity.component.ts
- src/app/explore/explore.component.html
- src/app/explore/explore.component.scss
- src/app/meta-campaign/meta-campaign.component.html
- src/app/meta-campaign/meta-campaign.component.scss
- src/assets/scss/_mixins.scss
Also
* extend `CampaignService` with the new endpoint to support this
* add a route resolver for better loading (see also DON-223)
* refactor SCSS to reduce duplication
* show info on campaign cards instead of Donate button when closed
> DON-242 - add Charity page

- src/app/donation-start/donation-start.component.ts
- DON-274 fix edge case bug where returning to 1st step and clicking next would create a new donation despite amount being the same
> DON-274 prevent multiple donations from being created

- src/app/campaign.model.ts
- src/app/charity-checkout-donation.model.spec.ts
- src/app/charity-checkout-donation.model.ts
- src/app/charity-checkout.service.ts
- src/app/donation-start/donation-start.component.ts
- src/app/donation.model.ts
- DON-275 start sending charity logo to enthuse + update models and tests
> DON-275 start sending charity logo to enthuse + update models and tests

- src/environments/environment.regression.ts
- Update regression SF endpoint
> Update regression SF endpoint

- src/app/donation-start/donation-start.component.ts
- DON-274 on submit, get the latest tip amount value
> DON-274 on submit, get the latest tip amount value

- src/app/ticker/ticker.component.html
- DON-304 stop showing ticker on champion fund pages
> DON-304 stop showing ticker on champion fund pages

- src/app/donation-start/donation-start.component.html
- src/assets/scss/_overwrite-mat.scss
- BG2-307 reduce scope of global classes to just donation input fields
> DON-307 reduce scope of global classes to just donation input fields

- src/app/donation-start/donation-start.component.html
- DON-309 lose heading + update copy + make font size smaller
> DON-309 lose heading + update copy + make font size smaller

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
DON-308 display placeholder outside of input field when in mobile + improve styling
**Mobile:**
**Tablet:**
**Desktop:**
> DON-308 display placeholder outside of input field when in mobile +improve styling

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
- DON-307 make tip input to tbg smaller and less instrusive
> DON-307 make tip input to tbg smaller and less instrusive

- src/app/app-routing.module.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
- redirect root path to CC20
N.B revert this PR after Staging user testing, then do the same change for this [ticket](https://thebiggive.atlassian.net/browse/DON-319)
> redirect root path to CC20

- src/app/ticker/ticker.component.scss
- DON-331 Move ticker and total onto seperate lines when in mobile, i.e < 450px
> DON-331 Move ticker and total onto seperate lines when in mobile, i.e < 450px

- src/app/donation-complete/donation-complete.component.ts
- DON-334 Share bitly link as the meta campaign equivalent during campaign times
> DON-334 Share bitly link as the meta campaign equivalent during campaign times

- src/app/campaign-card/campaign-card.component.html
- src/app/campaign-card/campaign-card.component.scss
- src/app/campaign-details-card/campaign-details-card.component.html
- src/app/campaign-details-card/campaign-details-card.component.scss
- src/assets/scss/_mixins.scss
- Add filter description headers + left align last child + rename css class for reusability
- DON-336 campaign card ordering and tweaks
> DON-336 campaign card ordering and tweaks

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
* DON-339 - fix overlapping timeout warnings
* DON-343 - fix form visibility just after campaign close
* fix incorrect match funds messaging in reuse dialog after expiry
> DON-339, DON-343 form logic

- src/app/donation-start/donation-start.component.ts
Also repopulate on resume, and don't explicitly validate, tipPercentage, to make form validation less brittle
> DON-338 - fix conditions for Stripe card mount & donation create

- src/app/donation-start/donation-start.component.ts
- src/app/donation.model.ts
- src/app/stripe.service.ts
- DON-349 expand donation model + new stripe service method + create payment method on submit
> DON-349 stripe create payment method

- src/app/explore/explore.component.ts
- src/app/filters/filters.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
- src/app/search.service.ts
Complete the move to a fully route-driven approach
and be more careful with event subscriptions
> DON-348 - simplify & fix search/filter logic

- src/app/meta-campaign/meta-campaign.component.ts
- src/app/navigation/navigation.component.html
- DON-352 replace routelink with href to kill the state of the page
> DON-352 replace routelink with href to kill the state of the page

- src/app/hero/hero.component.html
- src/app/hero/hero.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
Also improve fallback title when there is a fund with no logo
>  DON-353 - fix unreliable loading of hero fund data

- src/app/filters/filters.component.scss
- DON-344 add center align tag
> DON-344 add center align tag

- src/app/campaign.service.ts
Observed a handful of these last night. Suspect a rare loading race condition.
> INFRA-16 - avoid sending blank slug Campaign API requests

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- DON-360 add max length attributes which correlate to those defined in SF
> DON-360 add max length attributes which correlate to those defined in SF

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- DON-360 add validators in correct position + add validation messaging
> DON-360 add validators in correct position + add validation messaging

- src/app/footer/footer.component.html
- src/app/main-menu/main-menu.component.html
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- Stop homepage redirect + reinstate explore in nav menu
> Stop homepage redirect + reinstate explore in nav menu

- src/app/home/home.component.html
- Copy tweak as per request from Mr James Reed
> Copy tweak as per request from Mr James Reed

- package-lock.json
- package.json
- Upgrade fontawesome to 0.8.1
> DON-361 Upgrade fontawesome to 0.8.1

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
Also surface such errors in a more helpful place
> DON-363 - reset state appropriately after Stripe processing errors

- src/app/analytics.service.spec.ts
- src/app/campaign-details-card/campaign-details-card.component.spec.ts
- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign.model.ts
- src/app/campaign.service.spec.ts
- src/app/donation-start/donation-start.component.spec.ts
- src/app/hero/hero.component.spec.ts
- src/app/meta-campaign/meta-campaign.component.spec.ts
- src/app/ticker/ticker.component.spec.ts
- DON-369 remove gift handle usage
> DON-369 remove gift handle usage

- src/app/footer/footer.component.html
- src/app/main-menu/main-menu.component.html
- DON-370 DON-371 update nav bar and footer with latest campaigns
> DON-370 DON-371 update nav bar and footer with latest campaigns

- src/app/donation-start/donation-start.component.ts
Fix trying to jump to custom errors in invisible steps
> DON-374 - error/next fix

- src/app/donation-start/donation-start.component.ts
- src/app/stripe.service.ts
* fix currency case for Payment Request setup
* wait for needed donation setup before attempting to create Payment Request
> DON-233 fixes

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- src/app/stripe.service.ts
* include tip in amount to charge
* organise donation created subscriber code better
* show a method divider when PRB shown
> DON-233 fixes & tuning

- src/abstract.scss
- src/app/campaign-card/campaign-card.component.scss
- src/app/campaign-details-card/campaign-details-card.component.html
- src/app/campaign-details-card/campaign-details-card.component.scss
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.scss
- src/app/campaign-search-form/campaign-search-form.component.scss
- src/app/charity/charity.component.scss
- src/app/donation-complete/donation-complete.component.scss
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
- src/app/explore/explore.component.scss
- src/app/filters/filters-select-dialog.component.scss
- src/app/filters/filters.component.scss
- src/app/footer/footer.component.scss
- src/app/hero/hero.component.scss
- src/app/home/home.component.scss
- src/app/main-menu/main-menu.component.scss
- src/app/meta-campaign/meta-campaign.component.scss
- src/app/navigation/navigation.component.scss
- src/app/ticker/ticker.component.scss
- src/assets/scss/_overwrite-mat.scss
- src/assets/scss/_utilities.scss
- src/styles.scss
Aim to eliminate repeated and/or avoidable utility
styles, to make components smaller without visual impact
> DON-381 - refactor styles

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
- src/app/ticker/ticker.component.html
- src/app/ticker/ticker.component.ts
Vary the symbol shown against currency inputs and embedded
in additional copy, as well as that used for formatted outputs
> DON-383 - dynamic currency symbols

- src/app/app.module.ts
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
- src/assets/scss/_mat-theme.scss
Also rationalise existing tip calculations a bit.
> DON-394 - implement fee cover for alt model

- src/app/donation-complete/donation-complete.component.html
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
- src/app/donation.model.ts
- src/app/donation.service.ts
- src/app/stripe.service.ts
And various supporting changes to StripeService,
to support this and splitting up Payment Request Button
setup and payment
> DON-393 - reorder steps

- src/app/campaign-details/campaign-details.component.ts
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start.component.ts
- src/app/explore/explore.component.ts
- src/app/home/home.component.spec.ts
- src/app/home/home.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
- src/app/page-meta.service.spec.ts
- src/app/page-meta.service.ts
- src/index.html
- src/index.production.html
- src/index.regression.html
- src/index.staging.html
With variable base URI based on campaign currency.
Also remove hard-coded bits and use PageMetaService
across all main public pages instead.
> DON-403 - set canonical tags

- src/app/donation-start/donation-start.component.ts
Also only jump to 2nd step on modal confirmation to proceed _if_ donor's still on 1st step
> DON-408 – fix stepper header allowing skipping Stripe payment method

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- src/app/stripe.service.ts
This should make the Apple/Google Pay journey more intuitive
Also hide 'or' when hiding card number because a valid PRB payment method is already in place.
> DON-417 - jump to 'Receive updates' on PRB success

- src/app/donation-start/donation-start.component.ts
* fix missing element crash on Safari when Apple Pay method selection is done
* fix PRB not being set up when resuming a donation
> DON-417 further fixes

- src/app/donation-start/donation-start.component.ts
* DON-417, DON-393 - fix when we set billing address data on `donation`
* DON-417 - clear donation data more consistently; make PRBs work after donations are cancelled / restarted
* DON-417 - clear past Stripe error messages correctly once a valid card number is entered
> DON-417 QA fixes

- src/assets/scss/_overwrite-mat.scss
See https://github.com/angular/components/issues/10954
> DON-411 - fix checkbox labels on mobile

- src/app/donation-start/donation-start.component.ts
- src/app/stripe.service.ts
Changes from DON-417 have now been out for a while and PRBs seem to be working stably, so we can retire these logs. cc @alihejazi
> Remove temporary debug logs

- src/app/campaign-details/campaign-details.component.html
* DON-432 - give campaign details sections headers consistently
* DON-433 - re-order 'Campaign overview' tab contents
> DON-432, DON-433 – campaign details improvements

- angular.json
As per https://stackoverflow.com/a/67582075/2803757
> DON-401 - try updating `optimization` config

- src/app/campaign-card/campaign-card.component.html
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
- src/app/multicurrency-landing/multicurrency-landing.component.html
- src/app/multicurrency-landing/multicurrency-landing.component.scss
- src/app/multicurrency-landing/multicurrency-landing.component.ts
> DON-263 - update donation summary

- src/app/donation-start/donation-start-match-confirm-dialog.component.ts
- src/app/donation-start/donation-start-match-confirm-dialog.html
- src/app/donation-start/donation-start.component.ts
And style some modal copy for emphasis
> DON-364 - improve matching [partially] out copy

- server.ts
Hopefully fixes the survey widget which uses WebSockets
> DON-459 - update CSP rules for GetSiteControl

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
And add frontend maximum tip amount validation
> DON-465 - allow for new Create attempts after an error

- src/environments/environment.staging.ts
Reverts thebiggive/donate-frontend#632
> Revert "MAT-243 temporarily use test reCaptcha key so all requests are authorised"

- .circleci/config.yml
Have also deleted `SLACK_WEBHOOK` from direct project vars
> DON-506 – add new `slack` context

- src/app/analytics.service.ts
- src/app/donation-start/donation-start.component.ts
Simplify and hopefully fix the events we send during
donation page "checkout"
> DON-396 – eCommerce Google Analytics fixes

- src/app/analytics.service.ts
- src/app/app.module.ts
- src/app/donation-complete/donation-complete-set-password-dialog.component.ts
- src/app/donation-complete/donation-complete-set-password-dialog.html
- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.spec.ts
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
- src/app/donation.model.ts
- src/app/donation.service.ts
- src/app/identity.service.spec.ts
- src/app/identity.service.ts
- src/app/person.model.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
> DON-271 – set up Identity Person records during donation; offer to set a password afterwards

- package-lock.json
- package.json
- src/app/credentials.model.ts
- src/app/donation-complete/donation-complete-set-password-dialog.component.scss
- src/app/donation-complete/donation-complete-set-password-dialog.component.ts
- src/app/donation-complete/donation-complete-set-password-dialog.html
- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start.component.ts
- src/app/identity-jwt.model.ts
- src/app/identity.service.ts
* prompt for whether donor wants a long-term session
* login + upgrade their token if they want a session
* implement post-register auto-login including reCAPTCHA
* remove the original token if they don't want a session
* indicate on the thanks page when registration's done
> DON-236 – offer card saving and autologin

- package-lock.json
- package.json
- server.ts
- src/app/donation-complete/donation-complete-set-password-dialog.html
- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.scss
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
- src/app/donation-start/donation-start.component.ts
* [QA fix: allow server-rendered pages to call out to the ID API](https://github.com/thebiggive/donate-frontend/commit/6f51b6c4505b72e65a4bc7c1769d9980f8d89bc5)
* [make our ID content blocks look better; tighten check for showing person as logged in](https://github.com/thebiggive/donate-frontend/commit/4a6ff6285a10775ee667ccd2e7349ad5b7cbe28a)
* [fix missing label (in set password form)](https://github.com/thebiggive/donate-frontend/commit/7d00a29d3e38863f1860f8d0ff238deb67544531)
* [fix missing form billing data when using a saved card (Blocked proceeding at all due to hidden fields being invalid
in some cases.)](https://github.com/thebiggive/donate-frontend/commit/d38ca4366cbac00c681a899e5de4bfe5be632a72)
> DON-271 fixes + visual tuning

- package-lock.json
- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start-login-dialog.component.ts
- src/app/donation-start/donation-start-login-dialog.html
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
Vary them for Identity with distinct keys, as intended when
Identity backend was set up
> DON-271 – fix live reCAPTCHA configs

- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start-login-dialog.component.ts
- src/app/donation-start/donation-start-login-dialog.html
- src/app/donation-start/donation-start.component.ts
- src/environments/environment.ts
Reset captchas as appropriate
Also fix a local dev config thing and [DON-271 – tune post-register copy](https://github.com/thebiggive/donate-frontend/commit/ae73cbe3dc7e159cbe606dd8e93242a5f763aa1e)
> DON-270 – fix 2nd+ login attempts

- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start-login-dialog.component.ts
- src/app/donation-start/donation-start.component.ts
* Stop doing stuff sooner if our captcha callback needs no action
* Protect against use of expired captcha codes
> DON-535 – captcha expiry fix tweaks

- src/app/donation-complete/donation-complete.component.ts
Treat key missing donation props the same as a missing donation
> DON-534 – donation props safety

- src/app/buy-credits/buy-credits.component.ts
- src/app/donation-start/donation-start.component.ts
For existing ID users with no saved country
> DON-608 – fix "outside UK" default

- package-lock.json
- package.json
- src/app/footer/footer.component.html
- src/app/navigation/navigation.component.html
> DON-556 – add dynamic footer links

- src/app/buy-credits/buy-credits.component.html
- src/app/donation-complete/donation-complete.component.html
- src/app/donation-start/donation-start.component.html
- src/app/explore/explore.component.html
- src/app/meta-campaign/meta-campaign.component.html
ARIA label them appropriately throughout the app
> Fix accessibility of loading spinners

- package-lock.json
- package.json
- src/app/countries.ts
- src/app/donation-start/donation-start.component.ts
To improve build + runtime performance
> DON-606 – move country list into repo

- package-lock.json
- package.json
- src/app/donation-complete/donation-complete-set-password-dialog.html
- src/app/donation-start/donation-start-match-confirm-dialog.html
- src/app/donation-start/donation-start-matching-expired-dialog.html
- src/app/donation-start/donation-start-offer-reuse-dialog.html
- src/app/login-modal/login-modal.html
- src/app/register-modal/register-modal.html
Support future styling. Don't change filters, as that one should be retired tomorrow
> DON-560 – wrap Material Dialogs we're keeping in new component

- package-lock.json
- package.json
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/campaign-details/campaign-details.component.scss
- src/app/explore/explore.component.ts
- src/app/home/home.component.html
Including in campaign cards
Plus minor tidying
> DON-604 – use Angular navigation for all internal `<biggive-button>`s

- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign-details/campaign-details.component.ts
- src/app/campaign-details/campaign-details.module.ts
- src/app/donation-start/donation-start.component.ts
- src/app/meta-campaign/meta-campaign.component.html
- src/app/meta-campaign/meta-campaign.component.ts
- src/app/navigation.service.ts
Also optimise loading campaign detail page images again (scale appropriately, use webp)
> DON-645 – update metacampaign scroll position reinstatement

- src/app/meta-campaign/meta-campaign.component.html
- src/app/meta-campaign/meta-campaign.component.ts
> DON-669 – QA updates

- src/app/home/home.component.html
> DON-561: Replace youtube video on homepage

- package-lock.json
- package.json
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-details/campaign-details.component.ts
And update components to reverse hero style change
> DON-679 additional image fix

- package-lock.json
- package.json
Tweak campaign cards' badge position
> Get latest components

- src/app/campaign-details/campaign-details.component.html
Go to /explore now that home page doesn't list campaigns
> Update "all campaigns" link

- .circleci/config.yml
- package-lock.json
- package.json
Pin to Chromium 107 for now. Should hopefully also stop CI breaking every 6 weeks, at least for as long as 107 is supported in orbs.
> Pin CI to a specific Chrome version

- src/app/donation-start/donation-start.component.ts
> DON-703 – further simplify + improve email regex

- src/app/stripe.service.ts
This reverts commit 760579b952df89354e39ecc6a33875fdbf17e468.
> Revert "DON-697 temporarily add logging"

- src/app/app.component.html
Relies on new styles added in components PR 91, but should be safe to deploy now as nothing is being removed.
See https://github.com/thebiggive/components/pull/91
> DON-615: Add CSS styles to menu entries

- package-lock.json
- src/app/buy-credits/buy-credits.component.ts
- src/app/donation-start/donation-start.component.ts
- src/app/login-modal/login-modal.component.ts
- src/app/register-modal/register-modal.component.ts
- src/app/validators/patterns.ts
Clearing out some very quick "todo"s from my local copy
> Minor tidying

- src/app/home/home.component.html
(This is contrary to Jira spec, but make the page more consistent IMHO)
> DON-708: Add exclamation to GMF for consistency with CfC

- README.md
- link-components.sh
- package-lock.json
- package.json
- tsconfig.app.json
Screenshots show a mix of local changes within this codebase, and local changes in the components repo. Exactly where built code is saved and what we need to to do to update is slightly unclear to me.
XXX's are from local changes in the component repo
Yeah's are from local changes in the component repo
> DON-715: WIP allow use of local components

- package-lock.json
- package.json
See https://github.com/thebiggive/components/pull/110
> Use components version 1.0.194

- .circleci/config.yml
Reverts thebiggive/donate-frontend#864
> Revert "Remove failing Jira notification step."

- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.scss
Further layout tweaks based on QA feedback.
> Don 702 thanks tweaks ii

- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.ts
Also [Revert status-ignoring changes on](https://github.com/thebiggive/donate-frontend/commit/addf23638a687009489fee98653bbfa07300a15b) https://github.com/thebiggive/donate-frontend/commit/22439e98294959b3223e30cb4c0163487931c570
These are undocumented and seem most likely to have been used for local
tests and checked in in error
> DON-722 – fix campaign type metadata + safety

- src/app/app.component.ts
Donation form does not currently work correctly on new domain
> DON-725: Temporarily redirect away from new domain to old domain

- src/app/app.component.html
- src/app/app.component.ts
> main <- develop

- src/app/app.component.html
> DON-731 Reorder nav menu on donate to match menu on Wordpress

- src/app/donation-complete/donation-complete-set-password-dialog.component.ts
- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.ts
> ID-36: Display password related error as sent from server

- src/app/campaign-details-card/campaign-details-card.component.html
- src/app/campaign-details-card/campaign-details-card.component.scss
- src/app/campaign-details-card/campaign-details-card.component.spec.ts
- src/app/campaign-details-card/campaign-details-card.component.ts
- src/app/campaign-details/campaign-details.module.ts
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
- src/app/donation-start/donation-start.module.ts
Reverts thebiggive/donate-frontend#916
We don't want to release this because it remove the image at the top, which we'd rather keep.
> Revert "DON-586: Reskin Donation page's side/lower campaign info card"

- src/app/app-routing.ts
- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/featureFlags.ts
- src/app/identity.service.ts
- src/app/my-account/my-account-routing.module.ts
- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.spec.ts
- src/app/my-account/my-account.component.ts
- src/app/my-account/my-account.module.ts
This adds a new link "My Account" in the header that links to a new page to tell me who I am (or more specifically who I'm logged in to the site as).
There is a feature-flag so the link and the page only appear in non production like environments for now, i.e. my local copy of the site.
This is how it looks right now. Not pretty - I've been mostly dealing with just getting it working rather than making it look nice.
> DON-727: Add "My Account" page

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
> DON-586: Add Match Funded badge to donation page info card

- src/app/app.component.ts
- src/app/identity.service.ts
- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.scss
- src/app/my-account/my-account.component.spec.ts
- src/app/my-account/my-account.component.ts
- src/app/my-account/my-account.module.ts
> Don 727 profile page ii

- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.spec.ts
- src/app/my-account/my-account.component.ts
Work in progress - the display is currently looking like this: 
but we have quite a bit more data loaded ready to display - just need to decide which parts to display and where to put them:
I made this PR on top of DON-727 since I didn't want to merge that straight away.
> Don 732 see saved cards

- src/app/donation-start/donation-start.component.ts
- src/app/donation.service.ts
- src/app/my-account/my-account.component.ts
- src/environments/environment.interface.ts
- src/environments/environment.regression.ts
Makes the code easier to navigate and prevents mistakes when referring to properties of the environment
> Refactor: Strongly type environment

- src/app/donation.service.ts
- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.ts
This PR adds delete buttons to payment methods on the my account page as shown below. When I tried them on my local dev environment they didn't actually work (see [comment in matchbot](https://github.com/thebiggive/matchbot/pull/490/files#diff-1ee1d2c2677ebb2fc80c29931f8e47c9cf54497527f543613aa87c1d83fd43c7R38)), but I'd like to merge this and find out if they work in staging or not to know whether that's an issue specific to the way local connects to stripe.
> DON-724: Allow deleting saved payment method

- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.ts
I'm testing out a theory that including the environment files like this could be breaking the deploys
> DON-741: Remove "hidden by flag" notice

- README.md
- src/app/login-modal/login-modal.component.ts
- src/app/login-modal/login-modal.html
- src/app/register-modal/register-modal.html
Don-740 - login form error
- update login form error message for users entering invalid credentials - make more user friendly
- udate README.md to include fontawesome export
Before:
After:
> DON-740 - login form error

- src/app/buy-credits/buy-credits.component.html
- src/app/buy-credits/buy-credits.component.scss
- src/app/buy-credits/buy-credits.component.ts
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
- src/app/donation-start/donation-start.component.ts
The link is not showing up in the mobile menu, so we need another way at least for moblie users to get to this page. If we're giving it to mobile users we should give it to everyone.
> DON-727: Add buttons to link to my account page

- README.md
- src/app/app.component.ts
And document that we need to look out for this
> Fix server crashes from `window` use

- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.scss
- src/app/donation-complete/donation-complete.component.ts
> BG2-2294: Link from registration thanks to account page

- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.scss
> BG2-2294: Replace link with button for better contrast & accessibility

- src/app/donation-complete/donation-complete-set-password-dialog.component.ts
- src/app/donation-complete/donation-complete-set-password-dialog.html
> Hotfox remove login after donate (merge to develop)

- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.scss
Current layout desktop / mobile:
---
Adjusted layout desktop / mobile:
> DON-727: Account page layout adjusments

- src/app/buy-credits/buy-credits.component.html
- src/app/buy-credits/buy-credits.component.spec.ts
- src/app/buy-credits/buy-credits.component.ts
- src/app/buy-credits/buy-credits.module.ts
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- src/app/login-modal/login-modal.component.ts
- src/app/login-modal/login-modal.html
- src/app/register-modal/register-modal.component.ts
- src/app/register-modal/register-modal.html
- src/app/reset-password/reset-password.component.spec.ts
- src/app/reset-password/reset-password.component.ts
- src/environments/environment.interface.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
- src/index.staging.html
* Treat ID service as always-on to reduce complexity
* Handle captcha errors
* Set staging HTML `canonical` to the temporary domain
> DON-725 refinements

- src/app/home/home.component.html
> DON-745: Update total amount raised on Homepage

- src/app/featureFlags.ts
Not for merging until QA is done on affected work.
> DON-727: Release new profile page with payment method management

- src/app/buy-credits/buy-credits.component.html
- src/app/buy-credits/buy-credits.component.spec.ts
- src/app/buy-credits/buy-credits.component.ts
- src/app/buy-credits/buy-credits.module.ts
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- src/app/login-modal/login-modal.component.ts
- src/app/login-modal/login-modal.html
- src/app/register-modal/register-modal.component.ts
- src/app/register-modal/register-modal.html
- src/app/reset-password/reset-password.component.spec.ts
- src/app/reset-password/reset-password.component.ts
- src/environments/environment.interface.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
- src/index.staging.html
Reverts thebiggive/donate-frontend#979
I'm seeing this error now when I try to donate on staging 
although I don't get the error on my local. So I'll revert DON-725 in the hope that that might be the proximate cause and test on staging again. I think it's caused by a 401 response coming from `https://identity-staging.thebiggivetest.org.uk/v1/people/1edc33f2-0d04-68e8-8c5c-751fc46440cf`
> Revert "DON-725 refinements"

- src/app/buy-credits/buy-credits.component.html
- src/app/buy-credits/buy-credits.component.spec.ts
- src/app/buy-credits/buy-credits.component.ts
- src/app/buy-credits/buy-credits.module.ts
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.ts
- src/app/login-modal/login-modal.component.ts
- src/app/login-modal/login-modal.html
- src/app/register-modal/register-modal.component.ts
- src/app/register-modal/register-modal.html
- src/app/reset-password/reset-password.component.spec.ts
- src/app/reset-password/reset-password.component.ts
- src/environments/environment.interface.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
- src/index.staging.html
Reverts thebiggive/donate-frontend#982
Previous revert just exchanged one bug for another - after that was deployed clicking the Donate button after filling in payment details does nothing.
> Revert "Revert "DON-725 refinements""

- src/app/campaign-details/campaign-details.component.scss
- src/app/donation-start/donation-start.component.scss
- src/assets/scss/_mixins.scss
> BG-2292 align icons and text

- src/app/donation-complete/donation-complete-set-password-dialog.component.ts
- src/app/donation-complete/donation-complete-set-password-dialog.html
- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-complete/donation-complete.module.ts
The missing re-captcha tag in donation complete template was causing the issue Triggering full page refresh to update the menu
> DON-743: Bring back the option to keep user logged in after donation

- src/app/donation-complete/donation-complete.component.html
- src/app/home/home.component.html
Probably safe to merge as-is.
There's also a discussion to conclude around whether / why we have the property to vary this at all.
> DON-751 – make all buttons explicitly not (very) round

- src/app/home/HilightCard.ts
- src/app/home/hilightCard.ts
- src/app/home/home.component.html
- src/app/home/home.component.ts
So far this is pure refactoring, no changes made to homepage content or appearance. I think even if we didn't go further this has a bit of value as the new version seems like it might be slightly easier to edit, especially for non-devs, and is type checked.
> DON-735 - start preparing to take homepage content from Salesforce

- README.md
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/home/home.component.ts
Put config simplification and redirects back, now we know the new domain works in general.
> Revert "DON-726 – prepare a safer phased move to the new domain"
> This reverts commit 099bf7f5d20dca0dcfcf61c3f1d898e2a4abb2d9.
> DON-726 – Finalise domain move

- src/app/campaign.service.ts
The campaign is now closed and not accepting donations.
Before and after
> BG2-2231: Delete Turkey-Syria emergency appeal homepage card

- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
Signpost support for bank transfers up to £500k
> DON-748 – support larger donation credit balances

- package-lock.json
- server.ts
- src/app/app.component.ts
- src/app/donation-start/donation-start.component.ts
- src/app/meta-pixel.service.ts
- src/environments/environment.interface.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
See also https://github.com/thebiggive/donate-frontend/pull/249 This was tested & went live in 2020 and a lot of code is borrowed, so this PR is a close relative of that one. But it also includes measures to improve on the security and privacy implications of having the tag – more detail in commit and code comments.
> DON-746 – implement Meta Pixel

- src/environments/environment.interface.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
ID updates only to enable better QA » merging without review.
> DON-746 – use new Meta business account's Pixels

- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.scss
- src/app/my-account/my-account.component.spec.ts
- src/app/my-account/my-account.component.ts
- src/app/my-account/my-account.module.ts
- src/app/update-card-modal/update-card-modal.component.scss
- src/app/update-card-modal/update-card-modal.component.spec.ts
- src/app/update-card-modal/update-card-modal.component.ts
- src/app/update-card-modal/update-card-modal.html
This creates a new modal component for updating a card payment method.
There's more work to do, but the button for launching this modal is set to only show in the dev environment, so this should be safe to merge as-is, subject to review.
> DON-723: Create update payment method modal

- src/app/donation.service.ts
- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.scss
- src/app/my-account/my-account.component.ts
- src/app/my-account/my-account.module.ts
- src/app/update-card-modal/update-card-modal.component.ts
- src/app/update-card-modal/update-card-modal.html
https://github.com/thebiggive/matchbot/pull/518 should be merged and deployed before this one.
Error messages are displayed as sent by matchbot. There will be a PR to that which will make it pass on error messages verbatim from the Stripe API. They're not all exactly as I would choose to write them, but I think it's probably not worthwhile to map them to custom messages.
> DON-723: Allow editing saved card with modal

- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.scss
- src/app/my-account/my-account.component.ts
**Before / after mobile:**
**Before / after desktop:**
> Don 732 stack buttons on mobile

- src/app/donation-start/donation-start.component.html
- src/app/donation-start/donation-start.component.scss
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
Ticking any other card deselects the selected one, unticking opens the box to allow entering a new card.
> Don 734 choose between saved payment methods

- src/app/donation-start/donation-start.component.ts
Reverts thebiggive/donate-frontend#1040
> Revert "DON-759: add console logs to test captcha on staging, as it doesn't a…"

- src/app/donation-start/donation-start.component.ts
Reverts thebiggive/donate-frontend#1039
> Revert "DON-759 enforce captcha on every step during the donation journey"

- server.ts
- src/app/donation.service.ts
This reverts commit 8a45bbce44572e3b901af0a5e5f1efcf81cd050f.
> Revert "DON-523 – add various logging to help debug country detection in staging"

- src/app/donation-start/donation-start.component.ts
Not 100% sure if this will work, need to see it on staging.
> DON-759: Remove another unecassary captcha

- src/app/donation-start/donation-start.component.ts
Don't be so eager to create the donation - wait for the catpcha first.
> DON-759: Remove repeated captcha prompt

- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.ts
I forgot to do this when DON-723 passed QA. Just went to check it in prod and saw that it wasn't released.
> DON-732: Release edit card feature to production

- src/app/home/cardsForMetaCampaigns.spec.ts
- src/app/home/cardsForMetaCampaigns.ts
- src/app/home/home.component.ts
Includes logic to keep the home page as it is for now, and then change to the below when the clock on the users' computer ticks past noon UK time on Thursday.
> Don 761 gmf card update

- src/app/donation-start/donation-start.component.ts
I think we lost this while splitting / tidying `loadAuthedPersonInfo()`
> DON-762 – load credit balance on login

- src/app/home/cardsForMetaCampaigns.spec.ts
- src/app/home/cardsForMetaCampaigns.ts
- src/app/home/home.component.ts
> Don 761 gmf update ii

- package-lock.json
- package.json
- server.ts
- src/app/app.module.ts
- src/app/donation-start/donation-start.component.spec.ts
- src/app/donation-start/donation-start.component.ts
- src/environments/environment.interface.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
Just page views + ecommerce conversion
(including tip / product breakdown)
for now
> DON-758 – add Matomo

- angular.json
https://stackoverflow.com/a/68163709
> modified angular.json to fix broken test runner

- src/app/home/HighlightCard.ts
- src/app/home/cardsForMetaCampaigns.spec.ts
- src/app/home/cardsForMetaCampaigns.ts
- Brand icon colour still needs to be updated #62CFC9
- Card should be updated after noon Thursday
> DON-771 Replace GMF card with K2M card

- src/app/home/home.component.html
> DON-765: Update total raised after GMF

- src/app/donation-start/donation-start-container/donation-start-container.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.scss
- src/app/donation-start/donation-start-container/donation-start-container.component.spec.ts
- src/app/donation-start/donation-start-container/donation-start-container.component.ts
- src/app/donation-start/donation-start-container/donation-start-container.module.ts
- src/app/donation-start/donation-start-login/donation-start-login.component.html
- src/app/donation-start/donation-start-login/donation-start-login.component.ts
- src/app/donation-start/donation-start-primary/donation-start-primary.component.html
- src/app/donation-start/donation-start-primary/donation-start-primary.component.scss
- src/app/donation-start/donation-start-primary/donation-start-primary.component.ts
I'm nibbling away at the top of `donation-start-primary.component.html` with a plan to leave nothing but the form in there.
> Don 704: Separate donation start header and use donation start login from donation start form

- src/app/donation-start/donation-start-container/donation-start-container.component.html
These were added just as a bookmark on a dev machine, shouldn't have been committed
> Remove X's added by mistake

- src/app/app-routing.ts
- src/app/donation-start/donation-start-container/donation-start-container.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.ts
- src/app/donation-start/donation-start-container/donation-start-container.module.ts
- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
- src/app/donation-start/donation-start-form/donation-start-form-new.component.scss
- src/app/donation-start/donation-start-form/donation-start-form-new.component.ts
- src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts
…old and new
To see the new WIP design for the donation stepper, replace 'donate' in the URL with 'donate-new-stepper' -e.g. visit http://localhost:4200/donate-new-stepper/a056900002OZfFAAA1
New stepper design is starting as a copy of the old and evolving from there. For now we've just removed the white background (letting the f4f4f4 grey show through from the website background) and added a drop shadow.
> DON-610: Start of new design for donate form stepper

- src/app/donation-start/donation-start-container/donation-start-container.component.ts
Following latest notes on ticket
> BG2-2342: Wait to load person info before displaying donation form

- src/app/donation-start/donation-start-container/donation-start-container.component.ts
Fixes bug that I just introduced this afternoon, was never live
> BG2-2342: Fix missing donation form for anonymous donor in user

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
This reverts commit e9645f0ebaff7bdf51d29a41062b96cecc3d0242.
Work in that commit was unfinished, merged by mistake
> Revert "DON-610: WIP donation stepper step 5"

- src/app/home/cardsForMetaCampaigns.ts
This should automatically change the home page as shown below at exactly noon on Monday - although the change only appears after the viewer refreshes the page.
from
to
> DON-779: Change kind  to mind card automatically at Noon on Monday

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.html
Give donors with funds a more helpful error
> DON-778 – improve donation maximum validation message

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.html
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.spec.ts
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.ts
Appearance is unchanged, but now the slider moves correctly with the mouse pointer, and also recalculates its position when the window is resized.
> DON-793: Fix movement of tip slider to match mouse

- src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.html
> DON-610: Show link to new stepper in non-production

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
- src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/validators/currency-max.ts
Reverts thebiggive/donate-frontend#1144
> Revert "DON-778: Let overidden donation limit completely replace standard limit", fix error message

- src/app/buy-credits/buy-credits.component.ts
- src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts
- src/app/donation.model.spec.ts
- src/app/donation.model.ts
- src/app/validators/currency-max.ts
- src/environments/environment.interface.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
This should not be deployed (and therefore maybe should not be merged to develop?) before changes from https://github.com/thebiggive/matchbot/pull/559 are in production.
> DON-772: Increase donation limit based on funds balance

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.html
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.scss
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.ts
> Don 797 slider styling

- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.html
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.ts
> DON-815: Keep slider tooltip visible at edges

- package-lock.json
- package.json
Seems to work, builds, tests passing and site loads on local. And will stop us doing things like:
(not that we have been doing that)
Needs more testing before merging for real, so this is just a spike I'm planning to close.
> DON-830: Upgrade to RxJS 7

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
> DON-806: padding and alignment on stripe badge

- package-lock.json
- src/app/app.module.ts
- src/app/donation-complete/donation-complete.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
* Reduce a bit of boilerplate with new route param bind to `@Input()` – doesn't seem to be a thing in route resolvers unfortunately
* Minor update to get bug fix that might impact our load performance (not tested with SSR locally)
> DON-836 – minor Angular 16 tuning

- package-lock.json
- src/app/app.module.ts
- src/app/donation-complete/donation-complete.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
Reverts thebiggive/donate-frontend#1195
I think this broke the thanks page - as discussed on slack.
> Revert "DON-836 – minor Angular 16 tuning"

- package-lock.json
- src/app/app.module.ts
- src/app/donation-complete/donation-complete.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
* Reduce a bit of boilerplate with new route param bind to `@Input()` – doesn't seem to be a thing in route resolvers unfortunately
* Minor update to get bug fix that might impact our load performance (not tested with SSR locally)
Basically same as https://github.com/thebiggive/donate-frontend/pull/1195 except using `ngOnInit()` appropriately in `DonationCompleteComponent`. This also lets us stop injecting `ActivatedRoute` in that case.
> DON-836 – minor Angular 16 tuning (mk II)

- src/app/donation-start/donation-start-secondary/donation-start-secondary.component.html
- src/app/donation-start/donation-start-secondary/donation-start-secondary.component.scss
> DON-845: added 'Match Funded' badge to highlight card on donate page

- src/app/donation-start/donation-start-container/donation-start-container.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.scss
> DON-838: Add match funds reserved banner over new stepper

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
- src/app/donation-start/donation-start-form/donation-start-form-new.component.scss
Video to show how this looks as the name of the charity changes:
[Screencast from 2023-07-27 11-52-59.webm](https://github.com/thebiggive/donate-frontend/assets/159481/056214e2-9bc4-4a69-b6b1-ca4531880179)
> Don 833 step1 spacing

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
- src/app/donation-start/donation-start-form/donation-start-form-new.component.scss
> Don 849 delete old stepper elements

- src/app/donation-start/donation-start-form/donation-start-form-parent.component.ts
> DON-862: Use tip drop down not slider by default in new stepper

- src/app/donation-complete/donation-complete.component.scss
> Don-851 thank you page issues

- .circleci/config.yml
* [fix cached paths for the test job; name it & its workflow better](https://github.com/thebiggive/donate-frontend/commit/22f1303e37370e799286674ac8a2aa7970dcd8b5)
* [cache deps in CI for S3 builds](https://github.com/thebiggive/donate-frontend/commit/aaaf371137de090bc637582d3613f289ef78481e)
* [cache deps/anything cacheable in "remote" Docker layers for ECR builds](https://github.com/thebiggive/donate-frontend/commit/c698eef1ba0db0bfc2737a5132e5dfcaf43d03b4)
> DON-871 – Dependency caching fixes + improvements

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/transfer-funds/transfer-funds.component.html
> Don-868 new stepper gift aid a11y changes

- src/app/donation-start/donation-start-form/donation-start-form-new.component.html
> DON-865: New stepper tip match fund copy change

- src/app/app-routing.ts
- src/app/campaign-stats-resolver.ts
- src/app/campaign-stats.model.ts
- src/app/campaign.service.ts
- src/app/home/home.component.html
- src/app/home/home.component.ts
- tsconfig.json
Temporarily using SF prod url to display live stats.
> DON-579: use new sf api to dysplay dynamic stats

- .circleci/config.yml
Setting `docker` config on a custom job this time, and parameter-ising it to reduce repeated boilerplate
> DON-871 – cache deps/anything cacheable in "remote" Docker layers for ECR builds

- src/app/donation-complete/donation-complete.component.html
- src/app/donation-complete/donation-complete.component.scss
- src/app/donation-complete/donation-complete.component.ts
…ation is complete
Ideally I'd like to just have the page title be read out and do this job, but I couldn't see a way to do that. Might be worth having an sr-only copy of the page title on all pages in the app?
> DON-870: Thank you page accessibility tweeks

- src/app/donation-start/donation-start-container/donation-start-container.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.scss
- src/app/donation-start/donation-start-container/donation-start-container.component.ts
Looks like the image was accidentally dropped in commit da0120
Before:
After:
> Restore campaign banner image on donate page

- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/donation.model.ts
- src/app/stripe.service.ts
A few small proposed tweaks to https://github.com/thebiggive/donate-frontend/pull/1302
> DON-893 tweaks

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/donation.model.ts
- src/app/donation.service.ts
- src/app/stripe.service.ts
Reverts thebiggive/donate-frontend#1306
Required matchbot changes are now in prod.
> Revert "Revert "DON-893: Ask Matchbot to confirm donation payments instead of c…""

- src/app/donation-start/donation-start-container/donation-start-container.module.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.scss
- src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/featureFlags.ts
WIP - we've set up Snack Bar to display errors for the first step. 
Todo: Similar for all other continue buttons where they can have errors -  steps 2 to 5
Consider moving the snackbar away from the bottom of the screen and making it more prominent.
> Don 819 ameliorate disabled buttons

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
Only affects dev environment for now, in common with other DON-819 work.
> DON-819: Use snackbar to show errors in stepper gift aid step

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.scss
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
Also showing an error for failure to create the donation with snackbar:
> Don 819 confirmation step show errors

- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
Reverts thebiggive/donate-frontend#1335
May be still broken but restoring so I can test in staging - we shouldn't need to do another deploy today.
> Revert "DON-889 – remove skip link for now"

- src/app/donation-start/donation-start-form/donation-start-form.component.ts
Not sure why this should be needed but it seems to fix the issue (subject to some more testing)
> DON-909: Reset tip value after showing contine dialog function

- src/app/donation-start/donation-start-form/donation-start-form.component.ts
When this field is set from code we may end up with just one decimal here, which would be invalid previously.
> DON-909: Allow tip amounts with only one decimal, e.g. 12.5 for £12.50

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/featureFlags.ts
For merging only after ticket has passed QA
> DON-819: Enable new error display in all environments

- src/app/home/home.component.ts
> DON-911: wgmf post campaign card tweak

- package-lock.json
- src/app/campaign-details/campaign-details.component.ts
- src/app/campaign-info/campaign-info.component.ts
- src/app/campaign.service.spec.ts
- src/app/campaign.service.ts
- src/app/explore/explore.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
See https://github.com/thebiggive/donate-frontend/pull/1334#discussion_r1348447756
> DON-906 refactors + lib patch

- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign-details/campaign-details.component.ts
- src/app/campaign-details/campaign-details.module.ts
- src/app/campaign.model.ts
- src/app/campaign.service.spec.ts
- src/app/campaign.service.ts
- src/app/donation-start/donation-start-container/donation-start-container.component.spec.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.scss
- src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/meta-campaign/meta-campaign.component.spec.ts
- src/environments/common.ts
- src/styles.scss
Campaign details page:
Donation start page:
> BG2-2385 – tell donors & stop donations when we know a campaign isn't working

- src/app/donation-start/donation-start-container/donation-start-container.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.ts
- src/app/donation-start/donation-start-login/donation-start-login.component.html
- src/app/donation-start/donation-start-login/donation-start-login.component.ts
- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.module.ts
* [DON-897 – show Donations Funds balance on My Account page](https://github.com/thebiggive/donate-frontend/commit/bafdd82c16a8dd9b2820342286e69d512c05bd8f)
* [DON-915 – retire (broken) in-page Logout button](https://github.com/thebiggive/donate-frontend/commit/b990311cc52e2cc2cc0d17447d11358dc6011cd4)
> DON-897, DON-915

- src/app/app.component.html
- src/app/featureFlags.ts
Reverts https://github.com/thebiggive/donate-frontend/pull/1342
> DON-889 – enable skip link everywhere

- src/app/meta-campaign/meta-campaign.component.ts
Ensure top child campaigns aren't server-cached
in memory in a way we didn't anticipate.
> DON-773 - meta-campaign recent children tweak

- src/app/app.component.ts
Not sure if this is related to the DON-904 error, but it's an avoidable crash and it could be related
> DON-904: Fix TypeError on headerEl.closeMobileMenuFromOutside

- src/app/stripe.service.ts
> DON-921: Fix wrong rounding for total used in payment request button

- package-lock.json
- package.json
Security related - please see ticket for discussion.
> DON-846: Upgrade helmet library to from 4.6.0 to 7.1.0

- src/app/app.component.ts
- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start-container/donation-start-container.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.ts
- src/app/donation-start/donation-start-login/donation-start-login.component.ts
- src/app/identity.service.ts
- src/app/my-account/my-account.component.ts
- src/app/transfer-funds/transfer-funds.component.ts
Hopefully also fixes JWT removal on logout not consistently taking effect.
Also reduces some extraneous Identity API calls and probably some unnecessary Subscriptions.
> DON-929 – improve menu + login state handling

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.scss
- src/assets/scss/_variables.scss
Improve the situation on small mobile breakpoints for charity names which are long-ish but don't exceed
20 characters
> DON-936 – tweak main amount input label

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
Until we understand why they [sometimes?] cause issues when puzzles show
> DON-937, DON-938 – revert latest captcha changes

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
Instead of trying to submit the whole form, which will almost always fail.
I suggest reviewing with whitespace diff off – I fixed some confusing indents where I was reading.
> DON-937 – make enter key call `next()` & proceed 1 step when section valid

- src/app/donation-complete/donation-complete.component.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/donation.model.ts
Reverts thebiggive/donate-frontend#1415
> Revert "DON-938 – rationalise various captcha + step management"

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/environments/environment.interface.ts
- src/environments/environment.production.ts
- src/environments/environment.regression.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
This isn't especially pretty, but may be useful for quite a lot of tasks developing the donation form. If it gets in the way feel free to rip it out.
> Show debug info on donation form on dev environment only

- src/app/login/login.component.ts
- src/styles.scss
Solution from https://stackoverflow.com/a/52293650/2526181
> Don-752: Da ba dee da ba di

- src/app/login-modal/login-modal.component.ts
- src/app/login/login.component.html
- src/app/login/login.component.scss
- src/app/login/login.component.ts
> DON-752: Improve login page error display

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/environments/environment.production.ts
- src/environments/environment.staging.ts
- src/environments/environment.ts
And retire specific A/B test config for now
> DON-949 – only include "variant B" Nov/Dec tip copy

- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.scss
Before:
After:
Please see recent comments on ticket when reviewing.
> DON-752: Add explore & transfer funds buttons to My Account page

- src/app/app-routing.ts
- src/app/login/login.component.html
- src/app/login/login.component.ts
- src/app/register/register.component.ts
> DON-752: Add link from login page to registration page.

- src/app/app-routing.ts
- src/app/app.component.html
- src/app/featureFlags.ts
> DON-752: Release login page to all environments

- src/app/donation-thanks/donation-thanks.component.html
- src/app/donation-thanks/donation-thanks.component.scss
> Don 945 vip donation cta fix

- src/app/donation-thanks/donation-thanks.component.html
- src/app/donation-thanks/donation-thanks.component.scss
Please see latest comment on ticket.
> Don 954 part 2

- src/app/donation-thanks/donation-thanks.component.html
- src/app/donation-thanks/donation-thanks.component.scss
> DON-954: Fix thanks page layout

- package-lock.json
- package.json
- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/app/home/home.module.ts
- src/main.ts
Desktop:
(no movement as all slides fit on screen at once)
Mobile:
[Screencast from 2024-01-31 17-20-36.webm](https://github.com/thebiggive/donate-frontend/assets/159481/60547498-93fb-4105-a3cd-b77b8a2154d0)
> DON-576: Replace "Charities we support" homepage grid with carousel

- src/app/fund.model.ts
- src/app/meta-campaign/meta-campaign.component.ts
See related PR in Salesforce for more discussion.
> DON-930: Use correct total figure for metacampaign ticker

- src/app/home/home.component.html
- src/app/home/home.component.scss
- Turn of autoplay
- Add previous and next buttons
buttons
I wanted to find a way to control the slider from TS code, so I tried following the instructions at https://swiperjs.com/element#parameters-as-props but I couldn't get that to work. Seems like we don't need it for now though, I've done everything in the HTML code.
If we like this then as part of the other carousel ticket I'll probably extract it out into a component.
> Don 576 charity carousel amends

- src/app/home/HighlightCard.spec.ts
- src/app/home/HighlightCard.ts
Showing the change of color and background only
> DON-735: Add specific styling for emergency card

- src/app/highlight-cards-resolver.ts
> DON-735: Make salesforce data driven homepage generally available

- src/app/app.component.html
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-info/campaign-info.component.html
- src/app/charity/charity.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.html
- src/app/donation-start/donation-start-login/donation-start-login.component.html
- src/app/donation-start/donation-start-match-confirm-dialog.html
- src/app/donation-start/donation-start-offer-reuse-dialog.html
- src/app/donation-thanks/donation-thanks.component.html
- src/app/explore/explore.component.html
- src/app/home/home.component.html
- src/app/login-modal/login-modal.html
- src/app/login/login.component.html
- src/app/login/login.component.ts
- src/app/meta-campaign/meta-campaign.component.html
- src/app/my-account/my-account.component.html
- src/app/popup-standalone/popup-standalone.component.ts
- src/app/register-modal/register-modal.html
- src/app/register/register.component.html
- src/app/register/register.component.ts
- src/app/reset-password/reset-password.component.html
- src/app/transfer-funds/transfer-funds.component.html
- src/app/update-card-modal/update-card-modal.html
Changes generated by running:
> ng generate @angular/core:control-flow
I suggest turning off whitestpace display when reviewing. As changes are autogenerated probably reviewing a sample is enough - may not be necassary to review every single change.
> DON-950: Migrate to use new Angular template control flow features

- src/app/donation-start/donation-start-form/donation-start-form.component.html
> DON-963: Change copy re tips

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/environments/environment.production.ts
Worked on this during pairing with @bdsl
> Don 962 gmf ab test

- src/app/app.component.ts
- src/app/campaign-details/campaign-details.component.ts
- src/app/campaign-info/campaign-info.component.ts
- src/app/charity/charity.component.ts
- src/app/donation-start/donation-start-container/donation-start-container.component.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.ts
- src/app/donation-start/donation-start-login/donation-start-login.component.ts
- src/app/donation-thanks/donation-thanks-set-password-dialog.component.ts
- src/app/donation-thanks/donation-thanks.component.ts
- src/app/explore/explore.component.ts
- src/app/home/home.component.ts
- src/app/login-modal/login-modal.component.ts
- src/app/login/login.component.ts
- src/app/meta-campaign/meta-campaign.component.ts
- src/app/my-account/my-account.component.ts
- src/app/popup-standalone/popup-standalone.component.ts
- src/app/register-modal/register-modal.component.ts
- src/app/register/register.component.ts
- src/app/reset-password/reset-password.component.ts
- src/app/transfer-funds/transfer-funds.component.ts
I used regex search and replace
> DON-950: Use new singular StyleUrl available in Angular 17

- src/app/app.component.html
- src/app/campaign-details/campaign-details.component.html
- src/app/campaign-info/campaign-info.component.html
- src/app/charity/charity.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-tipping-slider/donation-tipping-slider.component.html
- src/app/donation-start/donation-start-login/donation-start-login.component.html
- src/app/donation-start/donation-start-match-confirm-dialog.html
- src/app/donation-start/donation-start-offer-reuse-dialog.html
- src/app/donation-thanks/donation-thanks.component.html
- src/app/explore/explore.component.html
- src/app/home/home.component.html
- src/app/login-modal/login-modal.html
- src/app/login/login.component.html
- src/app/login/login.component.ts
- src/app/meta-campaign/meta-campaign.component.html
- src/app/my-account/my-account.component.html
- src/app/popup-standalone/popup-standalone.component.ts
- src/app/register-modal/register-modal.html
- src/app/register/register.component.html
- src/app/register/register.component.ts
- src/app/reset-password/reset-password.component.html
- src/app/transfer-funds/transfer-funds.component.html
- src/app/update-card-modal/update-card-modal.html
Repeat of https://github.com/thebiggive/donate-frontend/pull/1512
All changes made on CLI with one command as shown below:
```
donate-frontend$ ng generate @angular/core:control-flow
? Which path in your project should be migrated? ./
? Should the migration reformat your templates? Yes
IMPORTANT! This migration is in developer preview. Use with caution.
UPDATE src/app/my-account/my-account.component.html (4653 bytes)
UPDATE src/app/update-card-modal/update-card-modal.html (2137 bytes)
UPDATE src/app/explore/explore.component.html (3082 bytes)
UPDATE src/app/donation-thanks/donation-thanks.component.html (9932 bytes)
UPDATE src/app/reset-password/reset-password.component.html (2975 bytes)
UPDATE src/app/meta-campaign/meta-campaign.component.html (4314 bytes)
UPDATE …
```
> DON-950: Migrate to use new Angular template features

- src/app/meta-campaign/meta-campaign.component.ts
Reverts thebiggive/donate-frontend#1551
Frontend deploys to staging have been failing since this #1551 . Suspect that wasn't the cause but reverting in case.
> Revert "Fix ticker on fund pages"

- src/app/meta-campaign/meta-campaign.component.ts
Reverts thebiggive/donate-frontend#1553
Looking at https://app.circleci.com/pipelines/github/thebiggive/donate-frontend?branch=develop it seems like reverting did fix the build.
But I'm not sure whether to believe that, I don't get how the changes here would stop deploys specifically to staging env.
> Revert "Revert "Fix ticker on fund pages""

- .circleci/config.yml
Reverts thebiggive/donate-frontend#1555
> Revert "Turn off `docker_layer_caching`"

- src/app/transfer-funds/transfer-funds.component.html
- src/app/transfer-funds/transfer-funds.component.ts
> DON-975: Hide gift aid step in transfer funds form if custom tip of zero selected

- src/app/app-routing.ts
- src/app/donation.service.spec.ts
- src/app/donation.service.ts
- src/app/featureFlags.ts
- src/app/my-donations/my-donations.component.cy.ts
- src/app/my-donations/my-donations.component.html
- src/app/my-donations/my-donations.component.scss
- src/app/my-donations/my-donations.component.ts
> Don 983 past donations

- src/app/donation-thanks/donation-thanks.component.ts
- src/app/donation.model.ts
- src/app/my-donations/my-donations.component.html
- src/app/my-donations/my-donations.component.scss
- src/app/my-donations/my-donations.component.ts
> DON-983: Adjust copy for donation history page

- src/app/my-account/my-account.component.html
- src/app/my-account/my-account.component.scss
- src/app/my-account/my-account.component.ts
- src/app/my-donations/my-donations.component.scss
[Screencast from 2024-07-25 18-17-02.webm](https://github.com/user-attachments/assets/6ffe5b37-7225-4699-aab1-95e5a7f875d4)
> Don 983 link from my account

- package-lock.json
- package.json
- src/app/featureFlags.ts
- src/app/person.model.ts
- src/app/register/register.component.html
- src/app/register/register.component.ts
> Don 985: Add friendly captcha on registration form (dev env only)

- src/app/exact-currency.pipe.ts
- src/app/featureFlags.ts
- src/app/mandate.model.ts
- src/app/my-account/my-account.component.html
- src/app/my-regular-giving/my-regular-giving.component.html
> Don 1025 regular giving gift aid

- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign.model.ts
- src/app/campaign.service.spec.ts
- src/app/conversionTracking.service.ts
- src/app/donation-start/donation-start-container/donation-start-container.component.spec.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/donation-start/updateDonationFromForm.ts
- src/app/donation-thanks/donation-thanks.component.spec.ts
- src/app/donation.model.ts
- src/app/donation.service.spec.ts
- src/app/meta-campaign/meta-campaign.component.spec.ts
- src/app/transfer-funds/transfer-funds.component.ts
As discussed feeCover is a feature that we introduced a few years ago but haven't ever used and are not likely to use. Now removing to simplify existing code and correct implementation of new features.
Best reviewed with "hide whitespace" turned on, as there are some indentation changes.
> Don 983 no feecover

- src/app/my-regular-giving/my-regular-giving.component.html
- src/app/my-regular-giving/my-regular-giving.component.scss
> DON-1025: Restyle regular giving page to match donation history page

- src/app/mandate.model.ts
- src/app/my-regular-giving/my-regular-giving.component.html
> DON-1025: Show next expected payment date on regular giving mandate

- src/app/my-donations/my-donations.component.html
- src/app/my-donations/my-donations.component.ts
See ticket comments for details
> DON-983: My donations page tweaks

- src/app/stripe.service.ts
Reverts thebiggive/donate-frontend#1639
> Revert "DON-896: Don't show Link.com payment method option"

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/stripe.service.ts
Continuing work started by @NoelLH 
Comparing before and after - before (staging) on left, after (my local) on right. The content is slightly different as I'm logged into different accounts, as that's a much quicker way to see both side by side. Change here is purely about styling. Probably needs a bit more work.
> Don 1071 restyle stripe element

- .gitignore
- package.json
- src/app/app.component.html
- src/app/app.component.ts
- tsconfig.app.json
Just a temporary thing to speed up diagnosing this issue. As it only appears on staging server and deploys to staging take some time it was hard to be certain about which version I was looking at to see what worked and didn't yesterday.
> DON-1073: Show git commit ID near page footer

- .gitignore
- Dockerfile
- package.json
- src/app/app.component.html
- src/app/app.component.ts
- tsconfig.app.json
This reverts commit 644dac5fb7c69f749e4535f5f9c5f83d473106ce.
Only intented as a temporary change while working on DON-1073
> Revert "DON-1073: Reintroduce display of git commit ID on all pages"

- src/app/campaign.service.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/donation-thanks/donation-thanks.component.ts
- src/app/identity.service.ts
- src/app/meta-campaign/meta-campaign.component.ts
- src/app/page-meta.service.ts
- src/app/search.service.ts
I used `npx type-coverage -p tsconfig.app.json` to measure type covearge and npx type-coverage -p tsconfig.app.json --detail to find specific instances of `any` types.
Before:
npx type-coverage -p tsconfig.app.json
13598 / 14175 95.92%
type-coverage success.
After:
npx type-coverage -p tsconfig.app.json
13682 / 14181 96.48%
type-coverage success.
So the proportion of any types is reduced by 14%
> Increase type coverage

- src/app/donation-thanks/donation-thanks.component.html
> DON-1071: Adjust thanks page create account CTA copy

- src/app/credentials.model.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/donation-thanks/donation-thanks.component.ts
- src/app/featureFlags.ts
- src/app/login-modal/login-modal.component.ts
- src/app/login/login.component.html
- src/app/login/login.component.scss
- src/app/login/login.component.ts
- src/app/register/register.component.html
- src/app/register/register.component.ts
Do not merge until after https://github.com/thebiggive/identity/pull/157 is in prod to support friendly captcha on login in identity service
> DON-1072: Switch login form to friendly captcha

- src/assets/scss/_mixins.scss
Related to latest comment on Jira ticket
> DON-1072: Don't show border around empty div on thanks page

- src/app/app-routing.ts
- src/app/regular-giving/regular-giving.component.html
- src/app/regular-giving/regular-giving.component.scss
- src/app/regular-giving/regular-giving.component.ts
> DON-998: Show logged in donor details on regular giving page

- src/app/donor-account.service.ts
Safe-ish to merge now, but given live campaign it's probably best to do a MatchBot Production deploy first, then merge this to `develop`.
> Use clearer donor-account API endpoint

- src/app/app-routing.ts
- src/app/regular-giving/regular-giving.component.html
- src/app/regular-giving/regular-giving.component.ts
- src/app/regularGiving.service.ts
> Don 998 matchbot integration

- src/app/campaign-details/campaign-details.component.spec.ts
- src/app/campaign-details/campaign-details.component.ts
- src/app/campaign-details/campaign-details.module.ts
- src/app/donation-start/donation-start-container/donation-start-container.module.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.spec.ts
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/regular-giving/regular-giving.component.ts
- src/app/toast.service.ts
DON-998: remove repeated code by creating Toast service.
> Don 998 deduplicate code

- server.ts
Don't know for sure whether this will help, seems quicker to test by merging and deploying to staging than on local
> DON-961: Adjust method for hydrating BG components in server side render

- server.ts
Reverts thebiggive/donate-frontend#1739
That generated a whitescreen empty page on staging.
> Revert "DON-961: Adjust method for hydrating BG components in server side render"

- server.ts
…ended by Stripe
see https://docs.stripe.com/security/guide?csp=csp-js
> DON-1080: Restrict loading all external resources by default, only allow specific types of resources as needed

- server.ts
Should fix the errors I'm now seeing on staging.
> Don-1080: Loosen csp rules

- src/app/home/home.component.ts
Also moved declaration closer to usage to make it easier to see
> Fix CCClose date to allow redirect to happen this year

- src/app/donation-thanks/donation-thanks.component.html
- src/app/donation-thanks/donation-thanks.component.ts
Copy is made up by me just now so should be reviewed along with code changes
> MAT-386: Fix thank you page error display and rewrite copy

- src/assets/scss/_mixins.scss
("Back to campaign" on donate page, and "All [Participating/ChampionName] campaigns" on campaign details page)
Before:
After:
> DON-1086: Reduce font size in back buttons

- src/app/my-account/my-account.component.ts
> DON-1065: My account page copy tweaks as requested

- src/app/person.model.ts
- src/app/transfer-funds/transfer-funds.component.html
- src/app/transfer-funds/transfer-funds.component.scss
- src/app/transfer-funds/transfer-funds.component.ts
* [Clarify status & options when there is a current balance](https://github.com/thebiggive/donate-frontend/commit/f397af633deb35eeca971912eb0de19fed53b27d)
* [Surface recently_confirmed_tips_total; don't propose a new Donation Funds tip when it's >£0](https://github.com/thebiggive/donate-frontend/commit/43bf233a7b6539bdea78a2aadb78a213a225b928)
> DON-1108 – improve Donation Funds transfer page's post-transfer UX

- src/app/my-donations/my-donations.component.html
- src/app/my-donations/my-donations.component.scss
> DON-1066: Add "Regular Giving" badget for past donation

- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/donation.service.ts
- src/app/donorAccount.model.ts
- src/app/regular-giving/regular-giving.component.html
- src/app/regular-giving/regular-giving.component.ts
- src/app/stripe.service.ts
> Don 998 add stripe form on regular giving page

- src/app/login/login.component.ts
- src/app/my-account/my-account.component.ts
- src/app/my-donations/my-donations.component.ts
- src/app/my-regular-giving/my-regular-giving.component.ts
- src/app/page-meta.service.ts
- src/app/register/register.component.ts
Minor tweak to help with UX and verifying where the browser is in tests
> Page title tidying: Add for Login & Register; append ' – Big Give' consistently

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation.model.ts
- src/app/regular-giving/regular-giving.component.html
- src/app/regularGiving.service.ts
- src/app/transfer-funds/transfer-funds.component.html
Doesn't affect any user facing copy except on the regular giving page
> DON-115: Fix spelling of receive.

- src/app/campaign-details/campaign-details.component.html
- src/app/charity/charity.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.ts
- src/app/explore/explore.component.html
- src/app/regular-giving/regular-giving.component.html
- src/app/regular-giving/regular-giving.component.scss
- src/app/regular-giving/regular-giving.component.ts
> Don 1115 regular giving campaign page

- src/app/regular-giving/regular-giving.component.html
For merging after https://github.com/thebiggive/matchbot/pull/1199
> DON-1008: Remove warning message about missing matchbot implemenation

- src/app/my-account/my-account.component.ts
> Fix cut off 'Regular Giving' at some breakpoints

- src/app/app-routing.ts
- src/app/cancel-mandate/cancel-mandate.component.html
- src/app/cancel-mandate/cancel-mandate.component.scss
- src/app/cancel-mandate/cancel-mandate.component.ts
- src/app/mandate.model.ts
- src/app/mandate/mandate.component.html
- src/app/my-regular-giving/my-regular-giving.component.html
- src/app/ordinal.pipe.ts
- src/app/regularGiving.service.ts
> Don-1022: Add mandate cancellation form

- src/app/campaign.model.ts
- src/app/mandate.model.ts
- src/app/regular-giving/regular-giving.component.html
- src/app/regular-giving/regular-giving.component.spec.ts
- src/app/regular-giving/regular-giving.component.ts
…iving
Screenshot below for scenario where there are only £53 of match funds available when we load the campaign
And for the scenario where there are less than £3 of match funds available at the time the page loads (effectively zero):
> DON-1003: Improve insufficent match funds messaging for regular giving 

- src/app/mandate/mandate.component.html
- src/app/mandate/mandate.component.ts
- src/app/regular-giving/regular-giving.component.ts
- src/app/regularGiving.service.ts
PR stacked on top of #1886 
See also https://github.com/thebiggive/matchbot/pull/1234
If mandates were in live use in prod then the two PRs would need to be deployed simultaneously, but as they're not we can deploy in either order.
> Don 1119 regular giving 3 ds next action

- src/app/campaign-details/campaign-details.component.html
- src/app/campaign.service.ts
- src/app/donation-start/donation-start-container/donation-start-container.component.ts
- src/app/regular-giving/regular-giving.component.html
- src/app/regular-giving/regular-giving.component.ts
…when campaign end date has passed
> DON-995: Handle closed regular giving campaigns

- src/app/mandate.model.ts
- src/app/mandate/mandate.component.html
- src/app/mandate/mandate.component.scss
- src/app/mandate/mandate.component.ts
- src/app/my-regular-giving/my-regular-giving.component.html
- src/app/my-regular-giving/my-regular-giving.component.ts
> DON-995: Show mandate campaign ended status on "my regular giving" page

- src/app/regular-giving/regular-giving.component.html
> DON-1005: Reduce size of already existing mandate "View Mandate" button

- src/app/campaign-details/campaign-details.component.html
- src/app/donation-start/donation-start-container/donation-start-container.component.html
Reverts thebiggive/donate-frontend#1913
PR ready to merge when we don't need this copy any more
> Revert "BG2-2850: Add message about issue to top of donate and campaign pages"

- src/app/backendError.ts
- src/app/my-payment-methods/my-payment-methods.component.html
- src/app/my-payment-methods/my-payment-methods.component.ts
- src/app/regularGiving.service.ts
Requires accompanying change in matchbot
> DON-1021: Allow removing card used for regular giving.

- src/app/regular-giving/regular-giving.component.ts
Same as single donation counterpart mostly
> Remove listener & Stripe element on Regular Giving component destroy

- src/app/donation-thanks/donation-thanks.component.html
Breakage was not deployed to prod
Broken:
Fixed:
> DON-1126: Fix broken style for donation thank you header box

- src/app/register/register.component.html
This reverts commit 04ef8be947e81257baa14397d9ac90e9734f222d.
To merge after https://github.com/thebiggive/regression-tests/pull/189
> Reapply "ID-47: Vary button label on registration page"

- src/app/register/register.component.ts
I thought before that the error @Input to VerifyEmailComponent wasn't working, but testing now it does actually seem to work. Just adjusted the copy here.
> ID-47: Adjust error message

- src/app/featureFlags.ts
Changes the register page to generate an email verification token
> ID-47: Enable new account setup system

- src/app/featureFlags.ts
> MAT-411: Turn off flag for useMatchbotCampaignApi in prod

- src/app/featureFlags.ts
Reverts thebiggive/donate-frontend#1998
> Revert "MAT-411: Turn off flag for useMatchbotCampaignApi in prod"

- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/app/donation.service.ts
- src/app/regular-giving/regular-giving.component.ts
And revert previous fix effort.
> DON-1148 – send `stripeConfirmationTokenFutureUsage` when confirming donations

- src/app/explore/explore.component.html
> DON-1120: Switch explore header background to blue

- src/app/explore/explore.component.html
- src/app/featureFlags.ts
- src/app/home/home.component.html
- src/app/home/home.component.ts
- src/app/metaCampaign.model.ts
Will make the new home and explore banner images and layout appear in prod when deployed
> Don 1120 release new banners for production

- src/app/donation-start/donation-start-form/donation-start-form.component.html
- src/app/donation-start/donation-start-form/donation-start-form.component.scss
- src/app/donation-start/donation-start-form/donation-start-form.component.ts
- src/assets/scss/_mat-theme.scss
- src/environments/environment.production.ts
- src/environments/environment.staging.ts
And tidy up related things:
* switch default percentages to be whole numbers regardless of UI for consistency & a comparable test
* remove previous test copy variants
I have taken a guess at the UI for showing & hiding the Custom amount in the absence of a dropdown. A button-like link seems reasonably intuitive to me and close to what some similar sites do; although it is not really aligned with our design elements to date, I thought real buttons would be more prominent than we ideally want.
This raised some questions about the links' keyboard usability and accessibility generally – first flagged to me by our a11y lint package which is nice! I've tried to heed its suggestions without making things too disruptive – so I supported keyboard activation on focus with the two methods I would …
> BG2-2972 – start tip slider alternative interface
